using System;
using System.IO;
using EPPlusTest.TestHelpers;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using OfficeOpenXml;

namespace EPPlusTest.Table.PivotTable.PivotTableRefresh
{
	[TestClass]
	public class PivotTableRefreshFormLayoutTest
	{
		[TestMethod]
		[DeploymentItem(@"..\..\Workbooks\PivotTables\PivotTableFormLayouts.xlsx")]
		public void PivotTableFreshFormLayoutThreeRowFieldsFirstOutlineSecondTabularThirdCompactOneColumnField()
		{
			var file = new FileInfo("PivotTableFormLayouts.xlsx");
			Assert.IsTrue(file.Exists);
			using (var newFile = new TempTestFile())
			{
				string sheetName = "Sheet2";
				using (var package = new ExcelPackage(file))
				{
					var worksheet = package.Workbook.Worksheets[sheetName];
					var pivotTable = worksheet.PivotTables["PivotTable1"];
					package.Workbook.PivotCacheDefinitions.ForEach(c => c.UpdateData());
					ExcelPivotTableTest.CheckPivotTableAddress(new ExcelAddress("A1:F14"), pivotTable.Address);
					package.SaveAs(newFile.File);
				}
				TestHelperUtility.ValidateWorksheet(newFile.File, sheetName, new[]
				{
					new ExpectedCellValue(sheetName, 1, 1, "Sum of Net Change"),
					new ExpectedCellValue(sheetName, 1, 4, "Column Labels"),
					new ExpectedCellValue(sheetName, 2, 1, "Row Labels"),
					new ExpectedCellValue(sheetName, 2, 2, "Income/Balance"),
					new ExpectedCellValue(sheetName, 2, 3, "Debit/Credit"),
					new ExpectedCellValue(sheetName, 2, 4, "FALSE"),
					new ExpectedCellValue(sheetName, 2, 5, "TRUE"),
					new ExpectedCellValue(sheetName, 2, 6, "Grand Total"),
					new ExpectedCellValue(sheetName, 3, 1, "Begin-Total"),
					new ExpectedCellValue(sheetName, 3, 4, 0),
					new ExpectedCellValue(sheetName, 3, 5, 0),
					new ExpectedCellValue(sheetName, 3, 6, 0),
					new ExpectedCellValue(sheetName, 4, 2, "Balance Sheet"),
					new ExpectedCellValue(sheetName, 4, 3, "Both"),
					new ExpectedCellValue(sheetName, 4, 4, 0),
					new ExpectedCellValue(sheetName, 4, 5, 0),
					new ExpectedCellValue(sheetName, 4, 6, 0),
					new ExpectedCellValue(sheetName, 5, 3, "Credit"),
					new ExpectedCellValue(sheetName, 5, 4, 0),
					new ExpectedCellValue(sheetName, 5, 5, null),
					new ExpectedCellValue(sheetName, 5, 6, 0),
					new ExpectedCellValue(sheetName, 6, 2, "Balance Sheet Total"),
					new ExpectedCellValue(sheetName, 6, 4, 0),
					new ExpectedCellValue(sheetName, 6, 5, 0),
					new ExpectedCellValue(sheetName, 6, 6, 0),
					new ExpectedCellValue(sheetName, 7, 1, "End-Total"),
					new ExpectedCellValue(sheetName, 7, 4, 0),
					new ExpectedCellValue(sheetName, 7, 5, 1008245.16),
					new ExpectedCellValue(sheetName, 7, 6, 1008245.16),
					new ExpectedCellValue(sheetName, 8, 2, "Balance Sheet"),
					new ExpectedCellValue(sheetName, 8, 3, "Both"),
					new ExpectedCellValue(sheetName, 8, 4, 0),
					new ExpectedCellValue(sheetName, 8, 5, 613103.7),
					new ExpectedCellValue(sheetName, 8, 6, 613103.7),
					new ExpectedCellValue(sheetName, 9, 3, "Debit"),
					new ExpectedCellValue(sheetName, 9, 4, null),
					new ExpectedCellValue(sheetName, 9, 5, 395141.46),
					new ExpectedCellValue(sheetName, 9, 6, 395141.46),
					new ExpectedCellValue(sheetName, 10, 2, "Balance Sheet Total"),
					new ExpectedCellValue(sheetName, 10, 4, 0),
					new ExpectedCellValue(sheetName, 10, 5, 1008245.16),
					new ExpectedCellValue(sheetName, 10, 6, 1008245.16),
					new ExpectedCellValue(sheetName, 11, 1, "Posting"),
					new ExpectedCellValue(sheetName, 11, 4, 0),
					new ExpectedCellValue(sheetName, 11, 5, 149891.77),
					new ExpectedCellValue(sheetName, 11, 6, 149891.77),
					new ExpectedCellValue(sheetName, 12, 2, "Balance Sheet"),
					new ExpectedCellValue(sheetName, 12, 3, "Debit"),
					new ExpectedCellValue(sheetName, 12, 4, 0),
					new ExpectedCellValue(sheetName, 12, 5, 149891.77),
					new ExpectedCellValue(sheetName, 12, 6, 149891.77),
					new ExpectedCellValue(sheetName, 13, 2, "Balance Sheet Total"),
					new ExpectedCellValue(sheetName, 13, 4, 0),
					new ExpectedCellValue(sheetName, 13, 5, 149891.77),
					new ExpectedCellValue(sheetName, 13, 6, 149891.77),
					new ExpectedCellValue(sheetName, 14, 1, "Grand Total"),
					new ExpectedCellValue(sheetName, 14, 4, 0),
					new ExpectedCellValue(sheetName, 14, 5, 1158136.93),
					new ExpectedCellValue(sheetName, 14, 6, 1158136.93),
				});
			}
		}

		[TestMethod]
		[DeploymentItem(@"..\..\Workbooks\PivotTables\PivotTableFormLayouts.xlsx")]
		public void PivotTableFreshFormLayoutFourRowFieldsFirstCompactSecondTabularThirdOutlineFourTabularNoColumnFields()
		{
			var file = new FileInfo("PivotTableFormLayouts.xlsx");
			Assert.IsTrue(file.Exists);
			using (var newFile = new TempTestFile())
			{
				string sheetName = "Sheet2";
				using (var package = new ExcelPackage(file))
				{
					var worksheet = package.Workbook.Worksheets[sheetName];
					var pivotTable = worksheet.PivotTables["PivotTable2"];
					package.Workbook.PivotCacheDefinitions.ForEach(c => c.UpdateData());
					ExcelPivotTableTest.CheckPivotTableAddress(new ExcelAddress("A18:D48"), pivotTable.Address);
					package.SaveAs(newFile.File);
				}
				TestHelperUtility.ValidateWorksheet(newFile.File, sheetName, new[]
				{
				new ExpectedCellValue(sheetName, 18, 1, "Row Labels"),
				new ExpectedCellValue(sheetName, 18, 2, "Name"),
				new ExpectedCellValue(sheetName, 18, 3, "Income/Balance"),
				new ExpectedCellValue(sheetName, 18, 4, "Sum of Net Change"),
				new ExpectedCellValue(sheetName, 19, 1, "FALSE"),
				new ExpectedCellValue(sheetName, 19, 4, null),
				new ExpectedCellValue(sheetName, 20, 1, "Begin-Total"),
				new ExpectedCellValue(sheetName, 20, 2, "Accounts Receivable"),
				new ExpectedCellValue(sheetName, 20, 4, null),
				new ExpectedCellValue(sheetName, 21, 3, "Balance Sheet"),
				new ExpectedCellValue(sheetName, 21, 4, 0),
				new ExpectedCellValue(sheetName, 22, 2, "ASSETS"),
				new ExpectedCellValue(sheetName, 22, 4, null),
				new ExpectedCellValue(sheetName, 23, 3, "Balance Sheet"),
				new ExpectedCellValue(sheetName, 23, 4, 0),
				new ExpectedCellValue(sheetName, 24, 1, "End-Total"),
				new ExpectedCellValue(sheetName, 24, 2, "Liquid Assets, Total"),
				new ExpectedCellValue(sheetName, 24, 4, null),
				new ExpectedCellValue(sheetName, 25, 3, "Balance Sheet"),
				new ExpectedCellValue(sheetName, 25, 4, 0),
				new ExpectedCellValue(sheetName, 26, 1, "Posting"),
				new ExpectedCellValue(sheetName, 26, 2, "Cash"),
				new ExpectedCellValue(sheetName, 26, 4, null),
				new ExpectedCellValue(sheetName, 27, 3, "Balance Sheet"),
				new ExpectedCellValue(sheetName, 27, 4, 0),
				new ExpectedCellValue(sheetName, 28, 1, "TRUE"),
				new ExpectedCellValue(sheetName, 28, 4, null),
				new ExpectedCellValue(sheetName, 29, 1, "Begin-Total"),
				new ExpectedCellValue(sheetName, 29, 2, "Accounts Payable"),
				new ExpectedCellValue(sheetName, 29, 4, null),
				new ExpectedCellValue(sheetName, 30, 3, "Balance Sheet"),
				new ExpectedCellValue(sheetName, 30, 4, 0),
				new ExpectedCellValue(sheetName, 31, 1, "End-Total"),
				new ExpectedCellValue(sheetName, 31, 2, "Current Assets, Total"),
				new ExpectedCellValue(sheetName, 31, 4, null),
				new ExpectedCellValue(sheetName, 32, 3, "Balance Sheet"),
				new ExpectedCellValue(sheetName, 32, 4, 395141.46),
				new ExpectedCellValue(sheetName, 33, 2, "Fixed Assets, Total"),
				new ExpectedCellValue(sheetName, 33, 4, null),
				new ExpectedCellValue(sheetName, 34, 3, "Balance Sheet"),
				new ExpectedCellValue(sheetName, 34, 4, 0),
				new ExpectedCellValue(sheetName, 35, 2, "Inventory, Total"),
				new ExpectedCellValue(sheetName, 35, 4, null),
				new ExpectedCellValue(sheetName, 36, 3, "Balance Sheet"),
				new ExpectedCellValue(sheetName, 36, 4, 217962.24),
				new ExpectedCellValue(sheetName, 37, 2, "Securities, Total"),
				new ExpectedCellValue(sheetName, 37, 4, null),
				new ExpectedCellValue(sheetName, 38, 3, "Balance Sheet"),
				new ExpectedCellValue(sheetName, 38, 4, null),
				new ExpectedCellValue(sheetName, 39, 2, "TOTAL ASSETS"),
				new ExpectedCellValue(sheetName, 39, 4, null),
				new ExpectedCellValue(sheetName, 40, 3, "Balance Sheet"),
				new ExpectedCellValue(sheetName, 40, 4, 395141.46),
				new ExpectedCellValue(sheetName, 41, 1, "Posting"),
				new ExpectedCellValue(sheetName, 41, 2, "Customers, North America"),
				new ExpectedCellValue(sheetName, 41, 4, null),
				new ExpectedCellValue(sheetName, 42, 3, "Balance Sheet"),
				new ExpectedCellValue(sheetName, 42, 4, 149891.77),
				new ExpectedCellValue(sheetName, 43, 2, "Vendors, Domestic"),
				new ExpectedCellValue(sheetName, 43, 4, null),
				new ExpectedCellValue(sheetName, 44, 3, "Balance Sheet"),
				new ExpectedCellValue(sheetName, 44, 4, null),
				new ExpectedCellValue(sheetName, 45, 1, "(blank)"),
				new ExpectedCellValue(sheetName, 45, 4, null),
				new ExpectedCellValue(sheetName, 46, 1, "(blank)"),
				new ExpectedCellValue(sheetName, 46, 2, "(blank)"),
				new ExpectedCellValue(sheetName, 46, 4, null),
				new ExpectedCellValue(sheetName, 47, 3, "(blank)"),
				new ExpectedCellValue(sheetName, 47, 4, null),
				new ExpectedCellValue(sheetName, 48, 1, "Grand Total"),
				new ExpectedCellValue(sheetName, 48, 4, 1158136.93),
				});
			}
		}

		[TestMethod]
		[DeploymentItem(@"..\..\Workbooks\PivotTables\PivotTableFormLayouts.xlsx")]
		public void PivotTableFreshFormLayoutMultipleDataFieldsUniversalTabularFormEnabledThreeRowFieldsFirstDataFieldSecondOutlineThirdTabularTwoColumnFields()
		{
			var file = new FileInfo("PivotTableFormLayouts.xlsx");
			Assert.IsTrue(file.Exists);
			using (var newFile = new TempTestFile())
			{
				string sheetName = "Sheet2";
				using (var package = new ExcelPackage(file))
				{
					var worksheet = package.Workbook.Worksheets[sheetName];
					var pivotTable = worksheet.PivotTables["PivotTable3"];
					package.Workbook.PivotCacheDefinitions.ForEach(c => c.UpdateData());
					package.SaveAs(new FileInfo(@"C:\Users\mcl\Downloads\PivotTables\Output.xlsx"));
					ExcelPivotTableTest.CheckPivotTableAddress(new ExcelAddress("A52:K64"), pivotTable.Address);
					package.SaveAs(newFile.File);
				}
				TestHelperUtility.ValidateWorksheet(newFile.File, sheetName, new[]
				{
					new ExpectedCellValue(sheetName, 52, 4, "Blocked"),
					new ExpectedCellValue(sheetName, 52, 5, "Debit/Credit"),
					new ExpectedCellValue(sheetName, 53, 4, "FALSE"),
					new ExpectedCellValue(sheetName, 53, 7, "FALSE Total"),
					new ExpectedCellValue(sheetName, 53, 8, "TRUE"),
					new ExpectedCellValue(sheetName, 53, 10, "TRUE Total"),
					new ExpectedCellValue(sheetName, 53, 11, "Grand Total"),
					new ExpectedCellValue(sheetName, 54, 1, "Values"),
					new ExpectedCellValue(sheetName, 54, 2, "Income/Balance"),
					new ExpectedCellValue(sheetName, 54, 3, "Account Type"),
					new ExpectedCellValue(sheetName, 54, 4, "Both"),
					new ExpectedCellValue(sheetName, 54, 5, "Credit"),
					new ExpectedCellValue(sheetName, 54, 6, "Debit"),
					new ExpectedCellValue(sheetName, 54, 8, "Both"),
					new ExpectedCellValue(sheetName, 54, 9, "Debit"),
					new ExpectedCellValue(sheetName, 55, 1, "Sum of Net Change"),
					new ExpectedCellValue(sheetName, 55, 2, "Balance Sheet"),
					new ExpectedCellValue(sheetName, 55, 4, 0),
					new ExpectedCellValue(sheetName, 55, 5, 0),
					new ExpectedCellValue(sheetName, 55, 6, 0),
					new ExpectedCellValue(sheetName, 55, 7, 0),
					new ExpectedCellValue(sheetName, 55, 8, 613103.7),
					new ExpectedCellValue(sheetName, 55, 9, 545033.23),
					new ExpectedCellValue(sheetName, 55, 10, 1158136.93),
					new ExpectedCellValue(sheetName, 55, 11, 1158136.93),
					new ExpectedCellValue(sheetName, 56, 3, "Begin-Total"),
					new ExpectedCellValue(sheetName, 56, 4, 0),
					new ExpectedCellValue(sheetName, 56, 5, 0),
					new ExpectedCellValue(sheetName, 56, 6, null),
					new ExpectedCellValue(sheetName, 56, 7, 0),
					new ExpectedCellValue(sheetName, 56, 8, 0),
					new ExpectedCellValue(sheetName, 56, 9, null),
					new ExpectedCellValue(sheetName, 56, 10, 0),
					new ExpectedCellValue(sheetName, 56, 11, 0),
					new ExpectedCellValue(sheetName, 57, 3, "End-Total"),
					new ExpectedCellValue(sheetName, 57, 4, 0),
					new ExpectedCellValue(sheetName, 57, 5, null),
					new ExpectedCellValue(sheetName, 57, 6, null),
					new ExpectedCellValue(sheetName, 57, 7, 0),
					new ExpectedCellValue(sheetName, 57, 8, 613103.7),
					new ExpectedCellValue(sheetName, 57, 9, 395141.46),
					new ExpectedCellValue(sheetName, 57, 10, 1008245.16),
					new ExpectedCellValue(sheetName, 57, 11, 1008245.16),
					new ExpectedCellValue(sheetName, 58, 3, "Posting"),
					new ExpectedCellValue(sheetName, 58, 4, null),
					new ExpectedCellValue(sheetName, 58, 5, null),
					new ExpectedCellValue(sheetName, 58, 6, 0),
					new ExpectedCellValue(sheetName, 58, 7, 0),
					new ExpectedCellValue(sheetName, 58, 8, null),
					new ExpectedCellValue(sheetName, 58, 9, 149891.77),
					new ExpectedCellValue(sheetName, 58, 10, 149891.77),
					new ExpectedCellValue(sheetName, 58, 11, 149891.77),
					new ExpectedCellValue(sheetName, 59, 1, "Sum of Indentation"),
					new ExpectedCellValue(sheetName, 59, 2, "Balance Sheet"),
					new ExpectedCellValue(sheetName, 59, 4, 2),
					new ExpectedCellValue(sheetName, 59, 5, 2),
					new ExpectedCellValue(sheetName, 59, 6, 3),
					new ExpectedCellValue(sheetName, 59, 7, 7),
					new ExpectedCellValue(sheetName, 59, 8, 5),
					new ExpectedCellValue(sheetName, 59, 9, 9),
					new ExpectedCellValue(sheetName, 59, 10, 14),
					new ExpectedCellValue(sheetName, 59, 11, 21),
					new ExpectedCellValue(sheetName, 60, 3, "Begin-Total"),
					new ExpectedCellValue(sheetName, 60, 4, 0),
					new ExpectedCellValue(sheetName, 60, 5, 2),
					new ExpectedCellValue(sheetName, 60, 6, null),
					new ExpectedCellValue(sheetName, 60, 7, 2),
					new ExpectedCellValue(sheetName, 60, 8, 2),
					new ExpectedCellValue(sheetName, 60, 9, null),
					new ExpectedCellValue(sheetName, 60, 10, 2),
					new ExpectedCellValue(sheetName, 60, 11, 4),
					new ExpectedCellValue(sheetName, 61, 3, "End-Total"),
					new ExpectedCellValue(sheetName, 61, 4, 2),
					new ExpectedCellValue(sheetName, 61, 5, null),
					new ExpectedCellValue(sheetName, 61, 6, null),
					new ExpectedCellValue(sheetName, 61, 7, 2),
					new ExpectedCellValue(sheetName, 61, 8, 3),
					new ExpectedCellValue(sheetName, 61, 9, 3),
					new ExpectedCellValue(sheetName, 61, 10, 6),
					new ExpectedCellValue(sheetName, 61, 11, 8),
					new ExpectedCellValue(sheetName, 62, 3, "Posting"),
					new ExpectedCellValue(sheetName, 62, 4, null),
					new ExpectedCellValue(sheetName, 62, 5, null),
					new ExpectedCellValue(sheetName, 62, 6, 3),
					new ExpectedCellValue(sheetName, 62, 7, 3),
					new ExpectedCellValue(sheetName, 62, 8, null),
					new ExpectedCellValue(sheetName, 62, 9, 6),
					new ExpectedCellValue(sheetName, 62, 10, 6),
					new ExpectedCellValue(sheetName, 62, 11, 9),
					new ExpectedCellValue(sheetName, 63, 1, "Total Sum of Net Change"),
					new ExpectedCellValue(sheetName, 63, 4, 0),
					new ExpectedCellValue(sheetName, 63, 5, 0),
					new ExpectedCellValue(sheetName, 63, 6, 0),
					new ExpectedCellValue(sheetName, 63, 7, 0),
					new ExpectedCellValue(sheetName, 63, 8, 613103.7),
					new ExpectedCellValue(sheetName, 63, 9, 545033.23),
					new ExpectedCellValue(sheetName, 63, 10, 1158136.93),
					new ExpectedCellValue(sheetName, 63, 11, 1158136.93),
					new ExpectedCellValue(sheetName, 64, 1, "Total Sum of Indentation"),
					new ExpectedCellValue(sheetName, 64, 4, 2),
					new ExpectedCellValue(sheetName, 64, 5, 2),
					new ExpectedCellValue(sheetName, 64, 6, 3),
					new ExpectedCellValue(sheetName, 64, 7, 7),
					new ExpectedCellValue(sheetName, 64, 8, 5),
					new ExpectedCellValue(sheetName, 64, 9, 9),
					new ExpectedCellValue(sheetName, 64, 10, 14),
					new ExpectedCellValue(sheetName, 64, 11, 21),
				});
			}
		}

		[TestMethod]
		[DeploymentItem(@"..\..\Workbooks\PivotTables\PivotTableFormLayouts.xlsx")]
		public void PivotTableFreshFormLayoutMultipleDataFieldsUniversalTabularFormEnabledThreeRowFieldsFirstCompactSecondDataFieldThirdOutlineOneColumnField()
		{
			var file = new FileInfo("PivotTableFormLayouts.xlsx");
			Assert.IsTrue(file.Exists);
			using (var newFile = new TempTestFile())
			{
				string sheetName = "Sheet2";
				using (var package = new ExcelPackage(file))
				{
					var worksheet = package.Workbook.Worksheets[sheetName];
					var pivotTable = worksheet.PivotTables["PivotTable4"];
					package.Workbook.PivotCacheDefinitions.ForEach(c => c.UpdateData());
					ExcelPivotTableTest.CheckPivotTableAddress(new ExcelAddress("A68:F92"), pivotTable.Address);
					package.SaveAs(newFile.File);
				}
				TestHelperUtility.ValidateWorksheet(newFile.File, sheetName, new[]
				{
					new ExpectedCellValue(sheetName, 68, 3, "Column Labels"),
					new ExpectedCellValue(sheetName, 69, 1, "Row Labels"),
					new ExpectedCellValue(sheetName, 69, 2, "Blocked"),
					new ExpectedCellValue(sheetName, 69, 3, "Both"),
					new ExpectedCellValue(sheetName, 69, 4, "Credit"),
					new ExpectedCellValue(sheetName, 69, 5, "Debit"),
					new ExpectedCellValue(sheetName, 69, 6, "Grand Total"),
					new ExpectedCellValue(sheetName, 70, 1, "Begin-Total"),
					new ExpectedCellValue(sheetName, 70, 3, null),
					new ExpectedCellValue(sheetName, 70, 4, null),
					new ExpectedCellValue(sheetName, 70, 5, null),
					new ExpectedCellValue(sheetName, 70, 6, null),
					new ExpectedCellValue(sheetName, 71, 1, "Sum of Indentation"),
					new ExpectedCellValue(sheetName, 71, 2, "FALSE"),
					new ExpectedCellValue(sheetName, 71, 3, 0),
					new ExpectedCellValue(sheetName, 71, 4, 2),
					new ExpectedCellValue(sheetName, 71, 5, null),
					new ExpectedCellValue(sheetName, 71, 6, 2),
					new ExpectedCellValue(sheetName, 72, 2, "TRUE"),
					new ExpectedCellValue(sheetName, 72, 3, 2),
					new ExpectedCellValue(sheetName, 72, 4, null),
					new ExpectedCellValue(sheetName, 72, 5, null),
					new ExpectedCellValue(sheetName, 72, 6, 2),
					new ExpectedCellValue(sheetName, 73, 1, "Sum of Net Change"),
					new ExpectedCellValue(sheetName, 73, 2, "FALSE"),
					new ExpectedCellValue(sheetName, 73, 3, 0),
					new ExpectedCellValue(sheetName, 73, 4, 0),
					new ExpectedCellValue(sheetName, 73, 5, null),
					new ExpectedCellValue(sheetName, 73, 6, 0),
					new ExpectedCellValue(sheetName, 74, 2, "TRUE"),
					new ExpectedCellValue(sheetName, 74, 3, 0),
					new ExpectedCellValue(sheetName, 74, 4, null),
					new ExpectedCellValue(sheetName, 74, 5, null),
					new ExpectedCellValue(sheetName, 74, 6, 0),
					new ExpectedCellValue(sheetName, 75, 1, "Begin-Total Sum of Indentation"),
					new ExpectedCellValue(sheetName, 75, 3, 2),
					new ExpectedCellValue(sheetName, 75, 4, 2),
					new ExpectedCellValue(sheetName, 75, 5, null),
					new ExpectedCellValue(sheetName, 75, 6, 4),
					new ExpectedCellValue(sheetName, 76, 1, "Begin-Total Sum of Net Change"),
					new ExpectedCellValue(sheetName, 76, 3, 0),
					new ExpectedCellValue(sheetName, 76, 4, 0),
					new ExpectedCellValue(sheetName, 76, 5, null),
					new ExpectedCellValue(sheetName, 76, 6, 0),
					new ExpectedCellValue(sheetName, 77, 1, "End-Total"),
					new ExpectedCellValue(sheetName, 77, 3, null),
					new ExpectedCellValue(sheetName, 77, 4, null),
					new ExpectedCellValue(sheetName, 77, 5, null),
					new ExpectedCellValue(sheetName, 77, 6, null),
					new ExpectedCellValue(sheetName, 78, 1, "Sum of Indentation"),
					new ExpectedCellValue(sheetName, 78, 2, "FALSE"),
					new ExpectedCellValue(sheetName, 78, 3, 2),
					new ExpectedCellValue(sheetName, 78, 4, null),
					new ExpectedCellValue(sheetName, 78, 5, null),
					new ExpectedCellValue(sheetName, 78, 6, 2),
					new ExpectedCellValue(sheetName, 79, 2, "TRUE"),
					new ExpectedCellValue(sheetName, 79, 3, 3),
					new ExpectedCellValue(sheetName, 79, 4, null),
					new ExpectedCellValue(sheetName, 79, 5, 3),
					new ExpectedCellValue(sheetName, 79, 6, 6),
					new ExpectedCellValue(sheetName, 80, 1, "Sum of Net Change"),
					new ExpectedCellValue(sheetName, 80, 2, "FALSE"),
					new ExpectedCellValue(sheetName, 80, 3, 0),
					new ExpectedCellValue(sheetName, 80, 4, null),
					new ExpectedCellValue(sheetName, 80, 5, null),
					new ExpectedCellValue(sheetName, 80, 6, 0),
					new ExpectedCellValue(sheetName, 81, 2, "TRUE"),
					new ExpectedCellValue(sheetName, 81, 3, 613103.7),
					new ExpectedCellValue(sheetName, 81, 4, null),
					new ExpectedCellValue(sheetName, 81, 5, 395141.46),
					new ExpectedCellValue(sheetName, 81, 6, 1008245.16),
					new ExpectedCellValue(sheetName, 82, 1, "End-Total Sum of Indentation"),
					new ExpectedCellValue(sheetName, 82, 3, 5),
					new ExpectedCellValue(sheetName, 82, 4, null),
					new ExpectedCellValue(sheetName, 82, 5, 3),
					new ExpectedCellValue(sheetName, 82, 6, 8),
					new ExpectedCellValue(sheetName, 83, 1, "End-Total Sum of Net Change"),
					new ExpectedCellValue(sheetName, 83, 3, 613103.7),
					new ExpectedCellValue(sheetName, 83, 4, null),
					new ExpectedCellValue(sheetName, 83, 5, 395141.46),
					new ExpectedCellValue(sheetName, 83, 6, 1008245.16),
					new ExpectedCellValue(sheetName, 84, 1, "Posting"),
					new ExpectedCellValue(sheetName, 84, 3, null),
					new ExpectedCellValue(sheetName, 84, 4, null),
					new ExpectedCellValue(sheetName, 84, 5, null),
					new ExpectedCellValue(sheetName, 84, 6, null),
					new ExpectedCellValue(sheetName, 85, 1, "Sum of Indentation"),
					new ExpectedCellValue(sheetName, 85, 2, "FALSE"),
					new ExpectedCellValue(sheetName, 85, 3, null),
					new ExpectedCellValue(sheetName, 85, 4, null),
					new ExpectedCellValue(sheetName, 85, 5, 3),
					new ExpectedCellValue(sheetName, 85, 6, 3),
					new ExpectedCellValue(sheetName, 86, 2, "TRUE"),
					new ExpectedCellValue(sheetName, 86, 3, null),
					new ExpectedCellValue(sheetName, 86, 4, null),
					new ExpectedCellValue(sheetName, 86, 5, 6),
					new ExpectedCellValue(sheetName, 86, 6, 6),
					new ExpectedCellValue(sheetName, 87, 1, "Sum of Net Change"),
					new ExpectedCellValue(sheetName, 87, 2, "FALSE"),
					new ExpectedCellValue(sheetName, 87, 3, null),
					new ExpectedCellValue(sheetName, 87, 4, null),
					new ExpectedCellValue(sheetName, 87, 5, 0),
					new ExpectedCellValue(sheetName, 87, 6, 0),
					new ExpectedCellValue(sheetName, 88, 2, "TRUE"),
					new ExpectedCellValue(sheetName, 88, 3, null),
					new ExpectedCellValue(sheetName, 88, 4, null),
					new ExpectedCellValue(sheetName, 88, 5, 149891.77),
					new ExpectedCellValue(sheetName, 88, 6, 149891.77),
					new ExpectedCellValue(sheetName, 89, 1, "Posting Sum of Indentation"),
					new ExpectedCellValue(sheetName, 89, 3, null),
					new ExpectedCellValue(sheetName, 89, 4, null),
					new ExpectedCellValue(sheetName, 89, 5, 9),
					new ExpectedCellValue(sheetName, 89, 6, 9),
					new ExpectedCellValue(sheetName, 90, 1, "Posting Sum of Net Change"),
					new ExpectedCellValue(sheetName, 90, 3, null),
					new ExpectedCellValue(sheetName, 90, 4, null),
					new ExpectedCellValue(sheetName, 90, 5, 149891.77),
					new ExpectedCellValue(sheetName, 90, 6, 149891.77),
					new ExpectedCellValue(sheetName, 91, 1, "Total Sum of Indentation"),
					new ExpectedCellValue(sheetName, 91, 3, 7),
					new ExpectedCellValue(sheetName, 91, 4, 2),
					new ExpectedCellValue(sheetName, 91, 5, 12),
					new ExpectedCellValue(sheetName, 91, 6, 21),
					new ExpectedCellValue(sheetName, 92, 1, "Total Sum of Net Change"),
					new ExpectedCellValue(sheetName, 92, 3, 613103.7),
					new ExpectedCellValue(sheetName, 92, 4, 0),
					new ExpectedCellValue(sheetName, 92, 5, 545033.23),
					new ExpectedCellValue(sheetName, 92, 6, 1158136.93),
				});
			}
		}

		[TestMethod]
		[DeploymentItem(@"..\..\Workbooks\PivotTables\PivotTableFormLayouts.xlsx")]
		public void PivotTableFreshFormLayoutMultipleDataFieldsUniversalTabularFormEnabledFourRowFieldsFirstOutlineSecondCompactThirdDataFieldFourthTabularOneColumnField()
		{
			var file = new FileInfo("PivotTableFormLayouts.xlsx");
			Assert.IsTrue(file.Exists);
			using (var newFile = new TempTestFile())
			{
				string sheetName = "Sheet2";
				using (var package = new ExcelPackage(file))
				{
					var worksheet = package.Workbook.Worksheets[sheetName];
					var pivotTable = worksheet.PivotTables["PivotTable5"];
					package.Workbook.PivotCacheDefinitions.ForEach(c => c.UpdateData());
					ExcelPivotTableTest.CheckPivotTableAddress(new ExcelAddress("I68:M114"), pivotTable.Address);
					package.SaveAs(newFile.File);
				}
				TestHelperUtility.ValidateWorksheet(newFile.File, sheetName, new[]
				{
					new ExpectedCellValue(sheetName, 68, 12, "Column Labels"),
					new ExpectedCellValue(sheetName, 69, 9, "Row Labels"),
					new ExpectedCellValue(sheetName, 69, 10, "Blocked"),
					new ExpectedCellValue(sheetName, 69, 11, "Debit/Credit"),
					new ExpectedCellValue(sheetName, 69, 12, "Balance Sheet"),
					new ExpectedCellValue(sheetName, 69, 13, "Grand Total"),
					new ExpectedCellValue(sheetName, 70, 9, "Begin-Total"),
					new ExpectedCellValue(sheetName, 70, 12, null),
					new ExpectedCellValue(sheetName, 70, 13, null),
					new ExpectedCellValue(sheetName, 71, 10, "FALSE"),
					new ExpectedCellValue(sheetName, 71, 12, null),
					new ExpectedCellValue(sheetName, 71, 13, null),
					new ExpectedCellValue(sheetName, 72, 10, "Sum of Indentation"),
					new ExpectedCellValue(sheetName, 72, 11, "Both"),
					new ExpectedCellValue(sheetName, 72, 12, 0),
					new ExpectedCellValue(sheetName, 72, 13, 0),
					new ExpectedCellValue(sheetName, 73, 11, "Credit"),
					new ExpectedCellValue(sheetName, 73, 12, 2),
					new ExpectedCellValue(sheetName, 73, 13, 2),
					new ExpectedCellValue(sheetName, 74, 10, "Sum of Net Change"),
					new ExpectedCellValue(sheetName, 74, 11, "Both"),
					new ExpectedCellValue(sheetName, 74, 12, 0),
					new ExpectedCellValue(sheetName, 74, 13, 0),
					new ExpectedCellValue(sheetName, 75, 11, "Credit"),
					new ExpectedCellValue(sheetName, 75, 12, 0),
					new ExpectedCellValue(sheetName, 75, 13, 0),
					new ExpectedCellValue(sheetName, 76, 10, "FALSE Sum of Indentation"),
					new ExpectedCellValue(sheetName, 76, 12, 2),
					new ExpectedCellValue(sheetName, 76, 13, 2),
					new ExpectedCellValue(sheetName, 77, 10, "FALSE Sum of Net Change"),
					new ExpectedCellValue(sheetName, 77, 12, 0),
					new ExpectedCellValue(sheetName, 77, 13, 0),
					new ExpectedCellValue(sheetName, 78, 10, "TRUE"),
					new ExpectedCellValue(sheetName, 78, 12, null),
					new ExpectedCellValue(sheetName, 78, 13, null),
					new ExpectedCellValue(sheetName, 79, 10, "Sum of Indentation"),
					new ExpectedCellValue(sheetName, 79, 11, "Both"),
					new ExpectedCellValue(sheetName, 79, 12, 2),
					new ExpectedCellValue(sheetName, 79, 13, 2),
					new ExpectedCellValue(sheetName, 80, 10, "Sum of Net Change"),
					new ExpectedCellValue(sheetName, 80, 11, "Both"),
					new ExpectedCellValue(sheetName, 80, 12, 0),
					new ExpectedCellValue(sheetName, 80, 13, 0),
					new ExpectedCellValue(sheetName, 81, 10, "TRUE Sum of Indentation"),
					new ExpectedCellValue(sheetName, 81, 12, 2),
					new ExpectedCellValue(sheetName, 81, 13, 2),
					new ExpectedCellValue(sheetName, 82, 10, "TRUE Sum of Net Change"),
					new ExpectedCellValue(sheetName, 82, 12, 0),
					new ExpectedCellValue(sheetName, 82, 13, 0),
					new ExpectedCellValue(sheetName, 83, 9, "Begin-Total Sum of Indentation"),
					new ExpectedCellValue(sheetName, 83, 12, 4),
					new ExpectedCellValue(sheetName, 83, 13, 4),
					new ExpectedCellValue(sheetName, 84, 9, "Begin-Total Sum of Net Change"),
					new ExpectedCellValue(sheetName, 84, 12, 0),
					new ExpectedCellValue(sheetName, 84, 13, 0),
					new ExpectedCellValue(sheetName, 85, 9, "End-Total"),
					new ExpectedCellValue(sheetName, 85, 12, null),
					new ExpectedCellValue(sheetName, 85, 13, null),
					new ExpectedCellValue(sheetName, 86, 10, "FALSE"),
					new ExpectedCellValue(sheetName, 86, 12, null),
					new ExpectedCellValue(sheetName, 86, 13, null),
					new ExpectedCellValue(sheetName, 87, 10, "Sum of Indentation"),
					new ExpectedCellValue(sheetName, 87, 11, "Both"),
					new ExpectedCellValue(sheetName, 87, 12, 2),
					new ExpectedCellValue(sheetName, 87, 13, 2),
					new ExpectedCellValue(sheetName, 88, 10, "Sum of Net Change"),
					new ExpectedCellValue(sheetName, 88, 11, "Both"),
					new ExpectedCellValue(sheetName, 88, 12, 0),
					new ExpectedCellValue(sheetName, 88, 13, 0),
					new ExpectedCellValue(sheetName, 89, 10, "FALSE Sum of Indentation"),
					new ExpectedCellValue(sheetName, 89, 12, 2),
					new ExpectedCellValue(sheetName, 89, 13, 2),
					new ExpectedCellValue(sheetName, 90, 10, "FALSE Sum of Net Change"),
					new ExpectedCellValue(sheetName, 90, 12, 0),
					new ExpectedCellValue(sheetName, 90, 13, 0),
					new ExpectedCellValue(sheetName, 91, 10, "TRUE"),
					new ExpectedCellValue(sheetName, 91, 12, null),
					new ExpectedCellValue(sheetName, 91, 13, null),
					new ExpectedCellValue(sheetName, 92, 10, "Sum of Indentation"),
					new ExpectedCellValue(sheetName, 92, 11, "Both"),
					new ExpectedCellValue(sheetName, 92, 12, 3),
					new ExpectedCellValue(sheetName, 92, 13, 3),
					new ExpectedCellValue(sheetName, 93, 11, "Debit"),
					new ExpectedCellValue(sheetName, 93, 12, 3),
					new ExpectedCellValue(sheetName, 93, 13, 3),
					new ExpectedCellValue(sheetName, 94, 10, "Sum of Net Change"),
					new ExpectedCellValue(sheetName, 94, 11, "Both"),
					new ExpectedCellValue(sheetName, 94, 12, 613103.7),
					new ExpectedCellValue(sheetName, 94, 13, 613103.7),
					new ExpectedCellValue(sheetName, 95, 11, "Debit"),
					new ExpectedCellValue(sheetName, 95, 12, 395141.46),
					new ExpectedCellValue(sheetName, 95, 13, 395141.46),
					new ExpectedCellValue(sheetName, 96, 10, "TRUE Sum of Indentation"),
					new ExpectedCellValue(sheetName, 96, 12, 6),
					new ExpectedCellValue(sheetName, 96, 13, 6),
					new ExpectedCellValue(sheetName, 97, 10, "TRUE Sum of Net Change"),
					new ExpectedCellValue(sheetName, 97, 12, 1008245.16),
					new ExpectedCellValue(sheetName, 97, 13, 1008245.16),
					new ExpectedCellValue(sheetName, 98, 9, "End-Total Sum of Indentation"),
					new ExpectedCellValue(sheetName, 98, 12, 8),
					new ExpectedCellValue(sheetName, 98, 13, 8),
					new ExpectedCellValue(sheetName, 99, 9, "End-Total Sum of Net Change"),
					new ExpectedCellValue(sheetName, 99, 12, 1008245.16),
					new ExpectedCellValue(sheetName, 99, 13, 1008245.16),
					new ExpectedCellValue(sheetName, 100, 9, "Posting"),
					new ExpectedCellValue(sheetName, 100, 12, null),
					new ExpectedCellValue(sheetName, 100, 13, null),
					new ExpectedCellValue(sheetName, 101, 10, "FALSE"),
					new ExpectedCellValue(sheetName, 101, 12, null),
					new ExpectedCellValue(sheetName, 101, 13, null),
					new ExpectedCellValue(sheetName, 102, 10, "Sum of Indentation"),
					new ExpectedCellValue(sheetName, 102, 11, "Debit"),
					new ExpectedCellValue(sheetName, 102, 12, 3),
					new ExpectedCellValue(sheetName, 102, 13, 3),
					new ExpectedCellValue(sheetName, 103, 10, "Sum of Net Change"),
					new ExpectedCellValue(sheetName, 103, 11, "Debit"),
					new ExpectedCellValue(sheetName, 103, 12, 0),
					new ExpectedCellValue(sheetName, 103, 13, 0),
					new ExpectedCellValue(sheetName, 104, 10, "FALSE Sum of Indentation"),
					new ExpectedCellValue(sheetName, 104, 12, 3),
					new ExpectedCellValue(sheetName, 104, 13, 3),
					new ExpectedCellValue(sheetName, 105, 10, "FALSE Sum of Net Change"),
					new ExpectedCellValue(sheetName, 105, 12, 0),
					new ExpectedCellValue(sheetName, 105, 13, 0),
					new ExpectedCellValue(sheetName, 106, 10, "TRUE"),
					new ExpectedCellValue(sheetName, 106, 12, null),
					new ExpectedCellValue(sheetName, 106, 13, null),
					new ExpectedCellValue(sheetName, 107, 10, "Sum of Indentation"),
					new ExpectedCellValue(sheetName, 107, 11, "Debit"),
					new ExpectedCellValue(sheetName, 107, 12, 6),
					new ExpectedCellValue(sheetName, 107, 13, 6),
					new ExpectedCellValue(sheetName, 108, 10, "Sum of Net Change"),
					new ExpectedCellValue(sheetName, 108, 11, "Debit"),
					new ExpectedCellValue(sheetName, 108, 12, 149891.77),
					new ExpectedCellValue(sheetName, 108, 13, 149891.77),
					new ExpectedCellValue(sheetName, 109, 10, "TRUE Sum of Indentation"),
					new ExpectedCellValue(sheetName, 109, 12, 6),
					new ExpectedCellValue(sheetName, 109, 13, 6),
					new ExpectedCellValue(sheetName, 110, 10, "TRUE Sum of Net Change"),
					new ExpectedCellValue(sheetName, 110, 12, 149891.77),
					new ExpectedCellValue(sheetName, 110, 13, 149891.77),
					new ExpectedCellValue(sheetName, 111, 9, "Posting Sum of Indentation"),
					new ExpectedCellValue(sheetName, 111, 12, 9),
					new ExpectedCellValue(sheetName, 111, 13, 9),
					new ExpectedCellValue(sheetName, 112, 9, "Posting Sum of Net Change"),
					new ExpectedCellValue(sheetName, 112, 12, 149891.77),
					new ExpectedCellValue(sheetName, 112, 13, 149891.77),
					new ExpectedCellValue(sheetName, 113, 9, "Total Sum of Indentation"),
					new ExpectedCellValue(sheetName, 113, 12, 21),
					new ExpectedCellValue(sheetName, 113, 13, 21),
					new ExpectedCellValue(sheetName, 114, 9, "Total Sum of Net Change"),
					new ExpectedCellValue(sheetName, 114, 12, 1158136.93),
					new ExpectedCellValue(sheetName, 114, 13, 1158136.93),
				});
			}
		}

		[TestMethod]
		[DeploymentItem(@"..\..\Workbooks\PivotTables\PivotTableFormLayouts.xlsx")]
		public void PivotTableFreshFormLayoutMultipleDataFieldsUniversalOutlineFormEnabledThreeRowFieldsFirstDataFieldSecondTabularThirdOutlineTwoColumnFields()
		{
			var file = new FileInfo("PivotTableFormLayouts.xlsx");
			Assert.IsTrue(file.Exists);
			using (var newFile = new TempTestFile())
			{
				string sheetName = "Sheet2";
				using (var package = new ExcelPackage(file))
				{
					var worksheet = package.Workbook.Worksheets[sheetName];
					var pivotTable = worksheet.PivotTables["PivotTable6"];
					package.Workbook.PivotCacheDefinitions.ForEach(c => c.UpdateData());
					ExcelPivotTableTest.CheckPivotTableAddress(new ExcelAddress("A118:G140"), pivotTable.Address);
					package.SaveAs(newFile.File);
				}
				TestHelperUtility.ValidateWorksheet(newFile.File, sheetName, new[]
				{
					new ExpectedCellValue(sheetName, 118, 4, "Income/Balance"),
					new ExpectedCellValue(sheetName, 118, 5, "Blocked"),
					new ExpectedCellValue(sheetName, 119, 4, "Balance Sheet"),
					new ExpectedCellValue(sheetName, 119, 6, "Balance Sheet Total"),
					new ExpectedCellValue(sheetName, 120, 1, "Values"),
					new ExpectedCellValue(sheetName, 120, 2, "Account Type"),
					new ExpectedCellValue(sheetName, 120, 3, "Debit/Credit"),
					new ExpectedCellValue(sheetName, 120, 4, "FALSE"),
					new ExpectedCellValue(sheetName, 120, 5, "TRUE"),
					new ExpectedCellValue(sheetName, 121, 1, "Sum of Indentation"),
					new ExpectedCellValue(sheetName, 121, 4, null),
					new ExpectedCellValue(sheetName, 121, 5, null),
					new ExpectedCellValue(sheetName, 121, 6, null),
					new ExpectedCellValue(sheetName, 122, 2, "Begin-Total"),
					new ExpectedCellValue(sheetName, 122, 3, "Both"),
					new ExpectedCellValue(sheetName, 122, 4, 0),
					new ExpectedCellValue(sheetName, 122, 5, 2),
					new ExpectedCellValue(sheetName, 122, 6, 2),
					new ExpectedCellValue(sheetName, 123, 3, "Credit"),
					new ExpectedCellValue(sheetName, 123, 4, 2),
					new ExpectedCellValue(sheetName, 123, 5, null),
					new ExpectedCellValue(sheetName, 123, 6, 2),
					new ExpectedCellValue(sheetName, 124, 2, "Begin-Total Total"),
					new ExpectedCellValue(sheetName, 124, 4, 2),
					new ExpectedCellValue(sheetName, 124, 5, 2),
					new ExpectedCellValue(sheetName, 124, 6, 4),
					new ExpectedCellValue(sheetName, 125, 2, "End-Total"),
					new ExpectedCellValue(sheetName, 125, 3, "Both"),
					new ExpectedCellValue(sheetName, 125, 4, 2),
					new ExpectedCellValue(sheetName, 125, 5, 3),
					new ExpectedCellValue(sheetName, 125, 6, 5),
					new ExpectedCellValue(sheetName, 126, 3, "Debit"),
					new ExpectedCellValue(sheetName, 126, 4, null),
					new ExpectedCellValue(sheetName, 126, 5, 3),
					new ExpectedCellValue(sheetName, 126, 6, 3),
					new ExpectedCellValue(sheetName, 127, 2, "End-Total Total"),
					new ExpectedCellValue(sheetName, 127, 4, 2),
					new ExpectedCellValue(sheetName, 127, 5, 6),
					new ExpectedCellValue(sheetName, 127, 6, 8),
					new ExpectedCellValue(sheetName, 128, 2, "Posting"),
					new ExpectedCellValue(sheetName, 128, 3, "Debit"),
					new ExpectedCellValue(sheetName, 128, 4, 3),
					new ExpectedCellValue(sheetName, 128, 5, 6),
					new ExpectedCellValue(sheetName, 128, 6, 9),
					new ExpectedCellValue(sheetName, 129, 2, "Posting Total"),
					new ExpectedCellValue(sheetName, 129, 4, 3),
					new ExpectedCellValue(sheetName, 129, 5, 6),
					new ExpectedCellValue(sheetName, 129, 6, 9),
					new ExpectedCellValue(sheetName, 130, 1, "Sum of Net Change"),
					new ExpectedCellValue(sheetName, 130, 4, null),
					new ExpectedCellValue(sheetName, 130, 5, null),
					new ExpectedCellValue(sheetName, 130, 6, null),
					new ExpectedCellValue(sheetName, 131, 2, "Begin-Total"),
					new ExpectedCellValue(sheetName, 131, 3, "Both"),
					new ExpectedCellValue(sheetName, 131, 4, 0),
					new ExpectedCellValue(sheetName, 131, 5, 0),
					new ExpectedCellValue(sheetName, 131, 6, 0),
					new ExpectedCellValue(sheetName, 132, 3, "Credit"),
					new ExpectedCellValue(sheetName, 132, 4, 0),
					new ExpectedCellValue(sheetName, 132, 5, null),
					new ExpectedCellValue(sheetName, 132, 6, 0),
					new ExpectedCellValue(sheetName, 133, 2, "Begin-Total Total"),
					new ExpectedCellValue(sheetName, 133, 4, 0),
					new ExpectedCellValue(sheetName, 133, 5, 0),
					new ExpectedCellValue(sheetName, 133, 6, 0),
					new ExpectedCellValue(sheetName, 134, 2, "End-Total"),
					new ExpectedCellValue(sheetName, 134, 3, "Both"),
					new ExpectedCellValue(sheetName, 134, 4, 0),
					new ExpectedCellValue(sheetName, 134, 5, 613103.7),
					new ExpectedCellValue(sheetName, 134, 6, 613103.7),
					new ExpectedCellValue(sheetName, 135, 3, "Debit"),
					new ExpectedCellValue(sheetName, 135, 4, null),
					new ExpectedCellValue(sheetName, 135, 5, 395141.46),
					new ExpectedCellValue(sheetName, 135, 6, 395141.46),
					new ExpectedCellValue(sheetName, 136, 2, "End-Total Total"),
					new ExpectedCellValue(sheetName, 136, 4, 0),
					new ExpectedCellValue(sheetName, 136, 5, 1008245.16),
					new ExpectedCellValue(sheetName, 136, 6, 1008245.16),
					new ExpectedCellValue(sheetName, 137, 2, "Posting"),
					new ExpectedCellValue(sheetName, 137, 3, "Debit"),
					new ExpectedCellValue(sheetName, 137, 4, 0),
					new ExpectedCellValue(sheetName, 137, 5, 149891.77),
					new ExpectedCellValue(sheetName, 137, 6, 149891.77),
					new ExpectedCellValue(sheetName, 138, 2, "Posting Total"),
					new ExpectedCellValue(sheetName, 138, 4, 0),
					new ExpectedCellValue(sheetName, 138, 5, 149891.77),
					new ExpectedCellValue(sheetName, 138, 6, 149891.77),
					new ExpectedCellValue(sheetName, 139, 1, "Total Sum of Indentation"),
					new ExpectedCellValue(sheetName, 139, 4, 7),
					new ExpectedCellValue(sheetName, 139, 5, 14),
					new ExpectedCellValue(sheetName, 139, 6, 21),
					new ExpectedCellValue(sheetName, 140, 1, "Total Sum of Net Change"),
					new ExpectedCellValue(sheetName, 140, 4, 0),
					new ExpectedCellValue(sheetName, 140, 5, 1158136.93),
					new ExpectedCellValue(sheetName, 140, 6, 1158136.93),
				});
			}
		}

		[TestMethod]
		[DeploymentItem(@"..\..\Workbooks\PivotTables\PivotTableFormLayouts.xlsx")]
		public void PivotTableFreshFormLayoutMultipleDataFieldsUniversalOutlineFormEnabledThreeRowFieldsFirstTabularSecondDataFieldThirdCompactTwoColumnFields()
		{
			var file = new FileInfo("PivotTableFormLayouts.xlsx");
			Assert.IsTrue(file.Exists);
			using (var newFile = new TempTestFile())
			{
				string sheetName = "Sheet2";
				using (var package = new ExcelPackage(file))
				{
					var worksheet = package.Workbook.Worksheets[sheetName];
					var pivotTable = worksheet.PivotTables["PivotTable7"];
					package.Workbook.PivotCacheDefinitions.ForEach(c => c.UpdateData());
					ExcelPivotTableTest.CheckPivotTableAddress(new ExcelAddress("A143:G169"), pivotTable.Address);
					package.SaveAs(newFile.File);
				}
				TestHelperUtility.ValidateWorksheet(newFile.File, sheetName, new[]
				{
					new ExpectedCellValue(sheetName, 143, 4, "Column Labels"),
					new ExpectedCellValue(sheetName, 144, 4, "Balance Sheet"),
					new ExpectedCellValue(sheetName, 144, 6, "Balance Sheet Total"),
					new ExpectedCellValue(sheetName, 144, 7, "Grand Total"),
					new ExpectedCellValue(sheetName, 145, 1, "Row Labels"),
					new ExpectedCellValue(sheetName, 145, 2, "Values"),
					new ExpectedCellValue(sheetName, 145, 3, "Debit/Credit"),
					new ExpectedCellValue(sheetName, 145, 4, "FALSE"),
					new ExpectedCellValue(sheetName, 145, 5, "TRUE"),
					new ExpectedCellValue(sheetName, 146, 1, "Begin-Total"),
					new ExpectedCellValue(sheetName, 146, 2, "Sum of Indentation"),
					new ExpectedCellValue(sheetName, 146, 4, null),
					new ExpectedCellValue(sheetName, 146, 5, null),
					new ExpectedCellValue(sheetName, 146, 6, null),
					new ExpectedCellValue(sheetName, 146, 7, null),
					new ExpectedCellValue(sheetName, 147, 3, "Both"),
					new ExpectedCellValue(sheetName, 147, 4, 0),
					new ExpectedCellValue(sheetName, 147, 5, 2),
					new ExpectedCellValue(sheetName, 147, 6, 2),
					new ExpectedCellValue(sheetName, 147, 7, 2),
					new ExpectedCellValue(sheetName, 148, 3, "Credit"),
					new ExpectedCellValue(sheetName, 148, 4, 2),
					new ExpectedCellValue(sheetName, 148, 5, null),
					new ExpectedCellValue(sheetName, 148, 6, 2),
					new ExpectedCellValue(sheetName, 148, 7, 2),
					new ExpectedCellValue(sheetName, 149, 2, "Sum of Net Change"),
					new ExpectedCellValue(sheetName, 149, 4, null),
					new ExpectedCellValue(sheetName, 149, 5, null),
					new ExpectedCellValue(sheetName, 149, 6, null),
					new ExpectedCellValue(sheetName, 149, 7, null),
					new ExpectedCellValue(sheetName, 150, 3, "Both"),
					new ExpectedCellValue(sheetName, 150, 4, 0),
					new ExpectedCellValue(sheetName, 150, 5, 0),
					new ExpectedCellValue(sheetName, 150, 6, 0),
					new ExpectedCellValue(sheetName, 150, 7, 0),
					new ExpectedCellValue(sheetName, 151, 3, "Credit"),
					new ExpectedCellValue(sheetName, 151, 4, 0),
					new ExpectedCellValue(sheetName, 151, 5, null),
					new ExpectedCellValue(sheetName, 151, 6, 0),
					new ExpectedCellValue(sheetName, 151, 7, 0),
					new ExpectedCellValue(sheetName, 152, 1, "Begin-Total Sum of Indentation"),
					new ExpectedCellValue(sheetName, 152, 4, 2),
					new ExpectedCellValue(sheetName, 152, 5, 2),
					new ExpectedCellValue(sheetName, 152, 6, 4),
					new ExpectedCellValue(sheetName, 152, 7, 4),
					new ExpectedCellValue(sheetName, 153, 1, "Begin-Total Sum of Net Change"),
					new ExpectedCellValue(sheetName, 153, 4, 0),
					new ExpectedCellValue(sheetName, 153, 5, 0),
					new ExpectedCellValue(sheetName, 153, 6, 0),
					new ExpectedCellValue(sheetName, 153, 7, 0),
					new ExpectedCellValue(sheetName, 154, 1, "End-Total"),
					new ExpectedCellValue(sheetName, 154, 2, "Sum of Indentation"),
					new ExpectedCellValue(sheetName, 154, 4, null),
					new ExpectedCellValue(sheetName, 154, 5, null),
					new ExpectedCellValue(sheetName, 154, 6, null),
					new ExpectedCellValue(sheetName, 154, 7, null),
					new ExpectedCellValue(sheetName, 155, 3, "Both"),
					new ExpectedCellValue(sheetName, 155, 4, 2),
					new ExpectedCellValue(sheetName, 155, 5, 3),
					new ExpectedCellValue(sheetName, 155, 6, 5),
					new ExpectedCellValue(sheetName, 155, 7, 5),
					new ExpectedCellValue(sheetName, 156, 3, "Debit"),
					new ExpectedCellValue(sheetName, 156, 4, null),
					new ExpectedCellValue(sheetName, 156, 5, 3),
					new ExpectedCellValue(sheetName, 156, 6, 3),
					new ExpectedCellValue(sheetName, 156, 7, 3),
					new ExpectedCellValue(sheetName, 157, 2, "Sum of Net Change"),
					new ExpectedCellValue(sheetName, 157, 4, null),
					new ExpectedCellValue(sheetName, 157, 5, null),
					new ExpectedCellValue(sheetName, 157, 6, null),
					new ExpectedCellValue(sheetName, 157, 7, null),
					new ExpectedCellValue(sheetName, 158, 3, "Both"),
					new ExpectedCellValue(sheetName, 158, 4, 0),
					new ExpectedCellValue(sheetName, 158, 5, 613103.7),
					new ExpectedCellValue(sheetName, 158, 6, 613103.7),
					new ExpectedCellValue(sheetName, 158, 7, 613103.7),
					new ExpectedCellValue(sheetName, 159, 3, "Debit"),
					new ExpectedCellValue(sheetName, 159, 4, null),
					new ExpectedCellValue(sheetName, 159, 5, 395141.46),
					new ExpectedCellValue(sheetName, 159, 6, 395141.46),
					new ExpectedCellValue(sheetName, 159, 7, 395141.46),
					new ExpectedCellValue(sheetName, 160, 1, "End-Total Sum of Indentation"),
					new ExpectedCellValue(sheetName, 160, 4, 2),
					new ExpectedCellValue(sheetName, 160, 5, 6),
					new ExpectedCellValue(sheetName, 160, 6, 8),
					new ExpectedCellValue(sheetName, 160, 7, 8),
					new ExpectedCellValue(sheetName, 161, 1, "End-Total Sum of Net Change"),
					new ExpectedCellValue(sheetName, 161, 4, 0),
					new ExpectedCellValue(sheetName, 161, 5, 1008245.16),
					new ExpectedCellValue(sheetName, 161, 6, 1008245.16),
					new ExpectedCellValue(sheetName, 161, 7, 1008245.16),
					new ExpectedCellValue(sheetName, 162, 1, "Posting"),
					new ExpectedCellValue(sheetName, 162, 2, "Sum of Indentation"),
					new ExpectedCellValue(sheetName, 162, 4, null),
					new ExpectedCellValue(sheetName, 162, 5, null),
					new ExpectedCellValue(sheetName, 162, 6, null),
					new ExpectedCellValue(sheetName, 162, 7, null),
					new ExpectedCellValue(sheetName, 163, 3, "Debit"),
					new ExpectedCellValue(sheetName, 163, 4, 3),
					new ExpectedCellValue(sheetName, 163, 5, 6),
					new ExpectedCellValue(sheetName, 163, 6, 9),
					new ExpectedCellValue(sheetName, 163, 7, 9),
					new ExpectedCellValue(sheetName, 164, 2, "Sum of Net Change"),
					new ExpectedCellValue(sheetName, 164, 4, null),
					new ExpectedCellValue(sheetName, 164, 5, null),
					new ExpectedCellValue(sheetName, 164, 6, null),
					new ExpectedCellValue(sheetName, 164, 7, null),
					new ExpectedCellValue(sheetName, 165, 3, "Debit"),
					new ExpectedCellValue(sheetName, 165, 4, 0),
					new ExpectedCellValue(sheetName, 165, 5, 149891.77),
					new ExpectedCellValue(sheetName, 165, 6, 149891.77),
					new ExpectedCellValue(sheetName, 165, 7, 149891.77),
					new ExpectedCellValue(sheetName, 166, 1, "Posting Sum of Indentation"),
					new ExpectedCellValue(sheetName, 166, 4, 3),
					new ExpectedCellValue(sheetName, 166, 5, 6),
					new ExpectedCellValue(sheetName, 166, 6, 9),
					new ExpectedCellValue(sheetName, 166, 7, 9),
					new ExpectedCellValue(sheetName, 167, 1, "Posting Sum of Net Change"),
					new ExpectedCellValue(sheetName, 167, 4, 0),
					new ExpectedCellValue(sheetName, 167, 5, 149891.77),
					new ExpectedCellValue(sheetName, 167, 6, 149891.77),
					new ExpectedCellValue(sheetName, 167, 7, 149891.77),
					new ExpectedCellValue(sheetName, 168, 1, "Total Sum of Indentation"),
					new ExpectedCellValue(sheetName, 168, 4, 7),
					new ExpectedCellValue(sheetName, 168, 5, 14),
					new ExpectedCellValue(sheetName, 168, 6, 21),
					new ExpectedCellValue(sheetName, 168, 7, 21),
					new ExpectedCellValue(sheetName, 169, 1, "Total Sum of Net Change"),
					new ExpectedCellValue(sheetName, 169, 4, 0),
					new ExpectedCellValue(sheetName, 169, 5, 1158136.93),
					new ExpectedCellValue(sheetName, 169, 6, 1158136.93),
					new ExpectedCellValue(sheetName, 169, 7, 1158136.93),
				});
			}
		}

		[TestMethod]
		[DeploymentItem(@"..\..\Workbooks\PivotTables\PivotTableFormLayouts.xlsx")]
		public void PivotTableFreshFormLayoutMultipleDataFieldsUniversalOutlineFormEnabledFourRowFieldsFirstTabularSecondCompactThirdDataFieldFourthOutlineOneColumnField()
		{
			var file = new FileInfo("PivotTableFormLayouts.xlsx");
			Assert.IsTrue(file.Exists);
			using (var newFile = new TempTestFile())
			{
				string sheetName = "Sheet2";
				using (var package = new ExcelPackage(file))
				{
					var worksheet = package.Workbook.Worksheets[sheetName];
					var pivotTable = worksheet.PivotTables["PivotTable8"];
					package.Workbook.PivotCacheDefinitions.ForEach(c => c.UpdateData());
					ExcelPivotTableTest.CheckPivotTableAddress(new ExcelAddress("A174:E224"), pivotTable.Address);
					package.SaveAs(newFile.File);
				}
				TestHelperUtility.ValidateWorksheet(newFile.File, sheetName, new[]
				{
					new ExpectedCellValue(sheetName, 174, 4, "Column Labels"),
					new ExpectedCellValue(sheetName, 175, 1, "Row Labels"),
					new ExpectedCellValue(sheetName, 175, 2, "Debit/Credit"),
					new ExpectedCellValue(sheetName, 175, 3, "Blocked"),
					new ExpectedCellValue(sheetName, 175, 4, "Balance Sheet"),
					new ExpectedCellValue(sheetName, 175, 5, "Grand Total"),
					new ExpectedCellValue(sheetName, 176, 1, "Begin-Total"),
					new ExpectedCellValue(sheetName, 176, 2, "Both"),
					new ExpectedCellValue(sheetName, 176, 4, null),
					new ExpectedCellValue(sheetName, 176, 5, null),
					new ExpectedCellValue(sheetName, 177, 2, "Sum of Indentation"),
					new ExpectedCellValue(sheetName, 177, 4, null),
					new ExpectedCellValue(sheetName, 177, 5, null),
					new ExpectedCellValue(sheetName, 178, 3, "FALSE"),
					new ExpectedCellValue(sheetName, 178, 4, 0),
					new ExpectedCellValue(sheetName, 178, 5, 0),
					new ExpectedCellValue(sheetName, 179, 3, "TRUE"),
					new ExpectedCellValue(sheetName, 179, 4, 2),
					new ExpectedCellValue(sheetName, 179, 5, 2),
					new ExpectedCellValue(sheetName, 180, 2, "Sum of Net Change"),
					new ExpectedCellValue(sheetName, 180, 4, null),
					new ExpectedCellValue(sheetName, 180, 5, null),
					new ExpectedCellValue(sheetName, 181, 3, "FALSE"),
					new ExpectedCellValue(sheetName, 181, 4, 0),
					new ExpectedCellValue(sheetName, 181, 5, 0),
					new ExpectedCellValue(sheetName, 182, 3, "TRUE"),
					new ExpectedCellValue(sheetName, 182, 4, 0),
					new ExpectedCellValue(sheetName, 182, 5, 0),
					new ExpectedCellValue(sheetName, 183, 2, "Both Sum of Indentation"),
					new ExpectedCellValue(sheetName, 183, 4, 2),
					new ExpectedCellValue(sheetName, 183, 5, 2),
					new ExpectedCellValue(sheetName, 184, 2, "Both Sum of Net Change"),
					new ExpectedCellValue(sheetName, 184, 4, 0),
					new ExpectedCellValue(sheetName, 184, 5, 0),
					new ExpectedCellValue(sheetName, 185, 2, "Credit"),
					new ExpectedCellValue(sheetName, 185, 4, null),
					new ExpectedCellValue(sheetName, 185, 5, null),
					new ExpectedCellValue(sheetName, 186, 2, "Sum of Indentation"),
					new ExpectedCellValue(sheetName, 186, 4, null),
					new ExpectedCellValue(sheetName, 186, 5, null),
					new ExpectedCellValue(sheetName, 187, 3, "FALSE"),
					new ExpectedCellValue(sheetName, 187, 4, 2),
					new ExpectedCellValue(sheetName, 187, 5, 2),
					new ExpectedCellValue(sheetName, 188, 2, "Sum of Net Change"),
					new ExpectedCellValue(sheetName, 188, 4, null),
					new ExpectedCellValue(sheetName, 188, 5, null),
					new ExpectedCellValue(sheetName, 189, 3, "FALSE"),
					new ExpectedCellValue(sheetName, 189, 4, 0),
					new ExpectedCellValue(sheetName, 189, 5, 0),
					new ExpectedCellValue(sheetName, 190, 2, "Credit Sum of Indentation"),
					new ExpectedCellValue(sheetName, 190, 4, 2),
					new ExpectedCellValue(sheetName, 190, 5, 2),
					new ExpectedCellValue(sheetName, 191, 2, "Credit Sum of Net Change"),
					new ExpectedCellValue(sheetName, 191, 4, 0),
					new ExpectedCellValue(sheetName, 191, 5, 0),
					new ExpectedCellValue(sheetName, 192, 1, "Begin-Total Sum of Indentation"),
					new ExpectedCellValue(sheetName, 192, 4, 4),
					new ExpectedCellValue(sheetName, 192, 5, 4),
					new ExpectedCellValue(sheetName, 193, 1, "Begin-Total Sum of Net Change"),
					new ExpectedCellValue(sheetName, 193, 4, 0),
					new ExpectedCellValue(sheetName, 193, 5, 0),
					new ExpectedCellValue(sheetName, 194, 1, "End-Total"),
					new ExpectedCellValue(sheetName, 194, 2, "Both"),
					new ExpectedCellValue(sheetName, 194, 4, null),
					new ExpectedCellValue(sheetName, 194, 5, null),
					new ExpectedCellValue(sheetName, 195, 2, "Sum of Indentation"),
					new ExpectedCellValue(sheetName, 195, 4, null),
					new ExpectedCellValue(sheetName, 195, 5, null),
					new ExpectedCellValue(sheetName, 196, 3, "FALSE"),
					new ExpectedCellValue(sheetName, 196, 4, 2),
					new ExpectedCellValue(sheetName, 196, 5, 2),
					new ExpectedCellValue(sheetName, 197, 3, "TRUE"),
					new ExpectedCellValue(sheetName, 197, 4, 3),
					new ExpectedCellValue(sheetName, 197, 5, 3),
					new ExpectedCellValue(sheetName, 198, 2, "Sum of Net Change"),
					new ExpectedCellValue(sheetName, 198, 4, null),
					new ExpectedCellValue(sheetName, 198, 5, null),
					new ExpectedCellValue(sheetName, 199, 3, "FALSE"),
					new ExpectedCellValue(sheetName, 199, 4, 0),
					new ExpectedCellValue(sheetName, 199, 5, 0),
					new ExpectedCellValue(sheetName, 200, 3, "TRUE"),
					new ExpectedCellValue(sheetName, 200, 4, 613103.7),
					new ExpectedCellValue(sheetName, 200, 5, 613103.7),
					new ExpectedCellValue(sheetName, 201, 2, "Both Sum of Indentation"),
					new ExpectedCellValue(sheetName, 201, 4, 5),
					new ExpectedCellValue(sheetName, 201, 5, 5),
					new ExpectedCellValue(sheetName, 202, 2, "Both Sum of Net Change"),
					new ExpectedCellValue(sheetName, 202, 4, 613103.7),
					new ExpectedCellValue(sheetName, 202, 5, 613103.7),
					new ExpectedCellValue(sheetName, 203, 2, "Debit"),
					new ExpectedCellValue(sheetName, 203, 4, null),
					new ExpectedCellValue(sheetName, 203, 5, null),
					new ExpectedCellValue(sheetName, 204, 2, "Sum of Indentation"),
					new ExpectedCellValue(sheetName, 204, 4, null),
					new ExpectedCellValue(sheetName, 204, 5, null),
					new ExpectedCellValue(sheetName, 205, 3, "TRUE"),
					new ExpectedCellValue(sheetName, 205, 4, 3),
					new ExpectedCellValue(sheetName, 205, 5, 3),
					new ExpectedCellValue(sheetName, 206, 2, "Sum of Net Change"),
					new ExpectedCellValue(sheetName, 206, 4, null),
					new ExpectedCellValue(sheetName, 206, 5, null),
					new ExpectedCellValue(sheetName, 207, 3, "TRUE"),
					new ExpectedCellValue(sheetName, 207, 4, 395141.46),
					new ExpectedCellValue(sheetName, 207, 5, 395141.46),
					new ExpectedCellValue(sheetName, 208, 2, "Debit Sum of Indentation"),
					new ExpectedCellValue(sheetName, 208, 4, 3),
					new ExpectedCellValue(sheetName, 208, 5, 3),
					new ExpectedCellValue(sheetName, 209, 2, "Debit Sum of Net Change"),
					new ExpectedCellValue(sheetName, 209, 4, 395141.46),
					new ExpectedCellValue(sheetName, 209, 5, 395141.46),
					new ExpectedCellValue(sheetName, 210, 1, "End-Total Sum of Indentation"),
					new ExpectedCellValue(sheetName, 210, 4, 8),
					new ExpectedCellValue(sheetName, 210, 5, 8),
					new ExpectedCellValue(sheetName, 211, 1, "End-Total Sum of Net Change"),
					new ExpectedCellValue(sheetName, 211, 4, 1008245.16),
					new ExpectedCellValue(sheetName, 211, 5, 1008245.16),
					new ExpectedCellValue(sheetName, 212, 1, "Posting"),
					new ExpectedCellValue(sheetName, 212, 2, "Debit"),
					new ExpectedCellValue(sheetName, 212, 4, null),
					new ExpectedCellValue(sheetName, 212, 5, null),
					new ExpectedCellValue(sheetName, 213, 2, "Sum of Indentation"),
					new ExpectedCellValue(sheetName, 213, 4, null),
					new ExpectedCellValue(sheetName, 213, 5, null),
					new ExpectedCellValue(sheetName, 214, 3, "FALSE"),
					new ExpectedCellValue(sheetName, 214, 4, 3),
					new ExpectedCellValue(sheetName, 214, 5, 3),
					new ExpectedCellValue(sheetName, 215, 3, "TRUE"),
					new ExpectedCellValue(sheetName, 215, 4, 6),
					new ExpectedCellValue(sheetName, 215, 5, 6),
					new ExpectedCellValue(sheetName, 216, 2, "Sum of Net Change"),
					new ExpectedCellValue(sheetName, 216, 4, null),
					new ExpectedCellValue(sheetName, 216, 5, null),
					new ExpectedCellValue(sheetName, 217, 3, "FALSE"),
					new ExpectedCellValue(sheetName, 217, 4, 0),
					new ExpectedCellValue(sheetName, 217, 5, 0),
					new ExpectedCellValue(sheetName, 218, 3, "TRUE"),
					new ExpectedCellValue(sheetName, 218, 4, 149891.77),
					new ExpectedCellValue(sheetName, 218, 5, 149891.77),
					new ExpectedCellValue(sheetName, 219, 2, "Debit Sum of Indentation"),
					new ExpectedCellValue(sheetName, 219, 4, 9),
					new ExpectedCellValue(sheetName, 219, 5, 9),
					new ExpectedCellValue(sheetName, 220, 2, "Debit Sum of Net Change"),
					new ExpectedCellValue(sheetName, 220, 4, 149891.77),
					new ExpectedCellValue(sheetName, 220, 5, 149891.77),
					new ExpectedCellValue(sheetName, 221, 1, "Posting Sum of Indentation"),
					new ExpectedCellValue(sheetName, 221, 4, 9),
					new ExpectedCellValue(sheetName, 221, 5, 9),
					new ExpectedCellValue(sheetName, 222, 1, "Posting Sum of Net Change"),
					new ExpectedCellValue(sheetName, 222, 4, 149891.77),
					new ExpectedCellValue(sheetName, 222, 5, 149891.77),
					new ExpectedCellValue(sheetName, 223, 1, "Total Sum of Indentation"),
					new ExpectedCellValue(sheetName, 223, 4, 21),
					new ExpectedCellValue(sheetName, 223, 5, 21),
					new ExpectedCellValue(sheetName, 224, 1, "Total Sum of Net Change"),
					new ExpectedCellValue(sheetName, 224, 4, 1158136.93),
					new ExpectedCellValue(sheetName, 224, 5, 1158136.93),
				});
			}
		}
	}
}
