using System.IO;
using System.Linq;
using EPPlusTest.TestHelpers;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using OfficeOpenXml;

namespace EPPlusTest.Table.PivotTable.Filters
{
	[TestClass]
	public class ItemFiltersTests
	{
		#region Hidden Row/Column Items Tests
		[TestMethod]
		[DeploymentItem(@"..\..\Workbooks\PivotTables\PivotTableHiddenRowAndColumnItems.xlsx")]
		public void PivotTableWithHiddenRowAndColumnItems()
		{
			var file = new FileInfo("PivotTableHiddenRowAndColumnItems.xlsx");
			Assert.IsTrue(file.Exists);
			using (var newFile = new TempTestFile())
			{
				string sheetName = "Sheet4";
				using (var package = new ExcelPackage(file))
				{
					var worksheet = package.Workbook.Worksheets[sheetName];
					var pivotTable = worksheet.PivotTables["PivotTable1"];
					var cacheDefinition = package.Workbook.PivotCacheDefinitions.Single();
					cacheDefinition.UpdateData();
					ExcelPivotTableTest.CheckPivotTableAddress(new ExcelAddress("B2:O109"), pivotTable.Address);
					Assert.AreEqual(8, pivotTable.Fields.Count);
					package.SaveAs(newFile.File);
				}
				TestHelperUtility.ValidateWorksheet(newFile.File, sheetName, new[]
				{
					new ExpectedCellValue(sheetName, 2, 2, "Sum of Unit Cost"),
					new ExpectedCellValue(sheetName, 2, 3, "Column Labels"),
					new ExpectedCellValue(sheetName, 3, 3, "FINISHED"),
					new ExpectedCellValue(sheetName, 3, 7, "FINISHED Total"),
					new ExpectedCellValue(sheetName, 3, 8, "RESALE"),
					new ExpectedCellValue(sheetName, 3, 14, "RESALE Total"),
					new ExpectedCellValue(sheetName, 3, 15, "Grand Total"),
					new ExpectedCellValue(sheetName, 4, 2, "Row Labels"),
					new ExpectedCellValue(sheetName, 4, 4, "01587796"),
					new ExpectedCellValue(sheetName, 4, 5, "20000"),
					new ExpectedCellValue(sheetName, 4, 6, "32456123"),
					new ExpectedCellValue(sheetName, 4, 9, "10000"),
					new ExpectedCellValue(sheetName, 4, 10, "20000"),
					new ExpectedCellValue(sheetName, 4, 11, "30000"),
					new ExpectedCellValue(sheetName, 4, 12, "46558855"),
					new ExpectedCellValue(sheetName, 4, 13, "50000"),
					new ExpectedCellValue(sheetName, 5, 2, "15\" 1501 FP Flat Panel"),
					new ExpectedCellValue(sheetName, 5, 3, null),
					new ExpectedCellValue(sheetName, 5, 4, null),
					new ExpectedCellValue(sheetName, 5, 5, null),
					new ExpectedCellValue(sheetName, 5, 6, null),
					new ExpectedCellValue(sheetName, 5, 7, null),
					new ExpectedCellValue(sheetName, 5, 8, null),
					new ExpectedCellValue(sheetName, 5, 9, null),
					new ExpectedCellValue(sheetName, 5, 10, null),
					new ExpectedCellValue(sheetName, 5, 11, null),
					new ExpectedCellValue(sheetName, 5, 12, null),
					new ExpectedCellValue(sheetName, 5, 13, 18),
					new ExpectedCellValue(sheetName, 5, 14, 18),
					new ExpectedCellValue(sheetName, 5, 15, 18),
					new ExpectedCellValue(sheetName, 6, 2, "17\" M780 Monitor"),
					new ExpectedCellValue(sheetName, 6, 3, null),
					new ExpectedCellValue(sheetName, 6, 4, null),
					new ExpectedCellValue(sheetName, 6, 5, null),
					new ExpectedCellValue(sheetName, 6, 6, null),
					new ExpectedCellValue(sheetName, 6, 7, null),
					new ExpectedCellValue(sheetName, 6, 8, null),
					new ExpectedCellValue(sheetName, 6, 9, 9.7),
					new ExpectedCellValue(sheetName, 6, 10, null),
					new ExpectedCellValue(sheetName, 6, 11, null),
					new ExpectedCellValue(sheetName, 6, 12, null),
					new ExpectedCellValue(sheetName, 6, 13, 27),
					new ExpectedCellValue(sheetName, 6, 14, 36.7),
					new ExpectedCellValue(sheetName, 6, 15, 36.7),
					new ExpectedCellValue(sheetName, 7, 2, "18GB Ultra 160/M SCSI"),
					new ExpectedCellValue(sheetName, 7, 3, null),
					new ExpectedCellValue(sheetName, 7, 4, null),
					new ExpectedCellValue(sheetName, 7, 5, null),
					new ExpectedCellValue(sheetName, 7, 6, null),
					new ExpectedCellValue(sheetName, 7, 7, null),
					new ExpectedCellValue(sheetName, 7, 8, null),
					new ExpectedCellValue(sheetName, 7, 9, null),
					new ExpectedCellValue(sheetName, 7, 10, null),
					new ExpectedCellValue(sheetName, 7, 11, null),
					new ExpectedCellValue(sheetName, 7, 12, null),
					new ExpectedCellValue(sheetName, 7, 13, 16.2),
					new ExpectedCellValue(sheetName, 7, 14, 16.2),
					new ExpectedCellValue(sheetName, 7, 15, 16.2),
					new ExpectedCellValue(sheetName, 8, 2, "19\" M009 Monitor"),
					new ExpectedCellValue(sheetName, 8, 3, null),
					new ExpectedCellValue(sheetName, 8, 4, null),
					new ExpectedCellValue(sheetName, 8, 5, null),
					new ExpectedCellValue(sheetName, 8, 6, null),
					new ExpectedCellValue(sheetName, 8, 7, null),
					new ExpectedCellValue(sheetName, 8, 8, null),
					new ExpectedCellValue(sheetName, 8, 9, 18.5),
					new ExpectedCellValue(sheetName, 8, 10, null),
					new ExpectedCellValue(sheetName, 8, 11, null),
					new ExpectedCellValue(sheetName, 8, 12, null),
					new ExpectedCellValue(sheetName, 8, 13, 32.4),
					new ExpectedCellValue(sheetName, 8, 14, 50.9),
					new ExpectedCellValue(sheetName, 8, 15, 50.9),
					new ExpectedCellValue(sheetName, 9, 2, "20.4 GB ATA-66 IDE"),
					new ExpectedCellValue(sheetName, 9, 3, null),
					new ExpectedCellValue(sheetName, 9, 4, null),
					new ExpectedCellValue(sheetName, 9, 5, null),
					new ExpectedCellValue(sheetName, 9, 6, null),
					new ExpectedCellValue(sheetName, 9, 7, null),
					new ExpectedCellValue(sheetName, 9, 8, null),
					new ExpectedCellValue(sheetName, 9, 9, null),
					new ExpectedCellValue(sheetName, 9, 10, null),
					new ExpectedCellValue(sheetName, 9, 11, null),
					new ExpectedCellValue(sheetName, 9, 12, null),
					new ExpectedCellValue(sheetName, 9, 13, 16.2),
					new ExpectedCellValue(sheetName, 9, 14, 16.2),
					new ExpectedCellValue(sheetName, 9, 15, 16.2),
					new ExpectedCellValue(sheetName, 10, 2, "20/48x IDE CD ROM"),
					new ExpectedCellValue(sheetName, 10, 3, null),
					new ExpectedCellValue(sheetName, 10, 4, null),
					new ExpectedCellValue(sheetName, 10, 5, null),
					new ExpectedCellValue(sheetName, 10, 6, null),
					new ExpectedCellValue(sheetName, 10, 7, null),
					new ExpectedCellValue(sheetName, 10, 8, null),
					new ExpectedCellValue(sheetName, 10, 9, null),
					new ExpectedCellValue(sheetName, 10, 10, null),
					new ExpectedCellValue(sheetName, 10, 11, null),
					new ExpectedCellValue(sheetName, 10, 12, null),
					new ExpectedCellValue(sheetName, 10, 13, 18),
					new ExpectedCellValue(sheetName, 10, 14, 18),
					new ExpectedCellValue(sheetName, 10, 15, 18),
					new ExpectedCellValue(sheetName, 11, 2, "21\" UltraScan P1110"),
					new ExpectedCellValue(sheetName, 11, 3, null),
					new ExpectedCellValue(sheetName, 11, 4, null),
					new ExpectedCellValue(sheetName, 11, 5, null),
					new ExpectedCellValue(sheetName, 11, 6, null),
					new ExpectedCellValue(sheetName, 11, 7, null),
					new ExpectedCellValue(sheetName, 11, 8, null),
					new ExpectedCellValue(sheetName, 11, 9, null),
					new ExpectedCellValue(sheetName, 11, 10, null),
					new ExpectedCellValue(sheetName, 11, 11, null),
					new ExpectedCellValue(sheetName, 11, 12, null),
					new ExpectedCellValue(sheetName, 11, 13, 36),
					new ExpectedCellValue(sheetName, 11, 14, 36),
					new ExpectedCellValue(sheetName, 11, 15, 36),
					new ExpectedCellValue(sheetName, 12, 2, "24\" Ultrascan"),
					new ExpectedCellValue(sheetName, 12, 3, null),
					new ExpectedCellValue(sheetName, 12, 4, null),
					new ExpectedCellValue(sheetName, 12, 5, null),
					new ExpectedCellValue(sheetName, 12, 6, null),
					new ExpectedCellValue(sheetName, 12, 7, null),
					new ExpectedCellValue(sheetName, 12, 8, null),
					new ExpectedCellValue(sheetName, 12, 9, null),
					new ExpectedCellValue(sheetName, 12, 10, null),
					new ExpectedCellValue(sheetName, 12, 11, null),
					new ExpectedCellValue(sheetName, 12, 12, null),
					new ExpectedCellValue(sheetName, 12, 13, 41.4),
					new ExpectedCellValue(sheetName, 12, 14, 41.4),
					new ExpectedCellValue(sheetName, 12, 15, 41.4),
					new ExpectedCellValue(sheetName, 13, 2, "250MB Disks/2pack"),
					new ExpectedCellValue(sheetName, 13, 3, null),
					new ExpectedCellValue(sheetName, 13, 4, null),
					new ExpectedCellValue(sheetName, 13, 5, null),
					new ExpectedCellValue(sheetName, 13, 6, null),
					new ExpectedCellValue(sheetName, 13, 7, null),
					new ExpectedCellValue(sheetName, 13, 8, null),
					new ExpectedCellValue(sheetName, 13, 9, null),
					new ExpectedCellValue(sheetName, 13, 10, null),
					new ExpectedCellValue(sheetName, 13, 11, null),
					new ExpectedCellValue(sheetName, 13, 12, null),
					new ExpectedCellValue(sheetName, 13, 13, 1.8),
					new ExpectedCellValue(sheetName, 13, 14, 1.8),
					new ExpectedCellValue(sheetName, 13, 15, 1.8),
					new ExpectedCellValue(sheetName, 14, 2, "250MB Disks/4pack"),
					new ExpectedCellValue(sheetName, 14, 3, null),
					new ExpectedCellValue(sheetName, 14, 4, null),
					new ExpectedCellValue(sheetName, 14, 5, null),
					new ExpectedCellValue(sheetName, 14, 6, null),
					new ExpectedCellValue(sheetName, 14, 7, null),
					new ExpectedCellValue(sheetName, 14, 8, null),
					new ExpectedCellValue(sheetName, 14, 9, null),
					new ExpectedCellValue(sheetName, 14, 10, null),
					new ExpectedCellValue(sheetName, 14, 11, null),
					new ExpectedCellValue(sheetName, 14, 12, null),
					new ExpectedCellValue(sheetName, 14, 13, 3.6),
					new ExpectedCellValue(sheetName, 14, 14, 3.6),
					new ExpectedCellValue(sheetName, 14, 15, 3.6),
					new ExpectedCellValue(sheetName, 15, 2, "256 MB PC800 ECC"),
					new ExpectedCellValue(sheetName, 15, 3, null),
					new ExpectedCellValue(sheetName, 15, 4, null),
					new ExpectedCellValue(sheetName, 15, 5, null),
					new ExpectedCellValue(sheetName, 15, 6, null),
					new ExpectedCellValue(sheetName, 15, 7, null),
					new ExpectedCellValue(sheetName, 15, 8, null),
					new ExpectedCellValue(sheetName, 15, 9, null),
					new ExpectedCellValue(sheetName, 15, 10, null),
					new ExpectedCellValue(sheetName, 15, 11, null),
					new ExpectedCellValue(sheetName, 15, 12, null),
					new ExpectedCellValue(sheetName, 15, 13, 21.6),
					new ExpectedCellValue(sheetName, 15, 14, 21.6),
					new ExpectedCellValue(sheetName, 15, 15, 21.6),
					new ExpectedCellValue(sheetName, 16, 2, "27GB ATA-66 IDE"),
					new ExpectedCellValue(sheetName, 16, 3, null),
					new ExpectedCellValue(sheetName, 16, 4, null),
					new ExpectedCellValue(sheetName, 16, 5, null),
					new ExpectedCellValue(sheetName, 16, 6, null),
					new ExpectedCellValue(sheetName, 16, 7, null),
					new ExpectedCellValue(sheetName, 16, 8, null),
					new ExpectedCellValue(sheetName, 16, 9, null),
					new ExpectedCellValue(sheetName, 16, 10, null),
					new ExpectedCellValue(sheetName, 16, 11, null),
					new ExpectedCellValue(sheetName, 16, 12, null),
					new ExpectedCellValue(sheetName, 16, 13, 19.8),
					new ExpectedCellValue(sheetName, 16, 14, 19.8),
					new ExpectedCellValue(sheetName, 16, 15, 19.8),
					new ExpectedCellValue(sheetName, 17, 2, "36GB Ultra 160/M SCSI"),
					new ExpectedCellValue(sheetName, 17, 3, null),
					new ExpectedCellValue(sheetName, 17, 4, null),
					new ExpectedCellValue(sheetName, 17, 5, null),
					new ExpectedCellValue(sheetName, 17, 6, null),
					new ExpectedCellValue(sheetName, 17, 7, null),
					new ExpectedCellValue(sheetName, 17, 8, null),
					new ExpectedCellValue(sheetName, 17, 9, null),
					new ExpectedCellValue(sheetName, 17, 10, null),
					new ExpectedCellValue(sheetName, 17, 11, null),
					new ExpectedCellValue(sheetName, 17, 12, null),
					new ExpectedCellValue(sheetName, 17, 13, 27),
					new ExpectedCellValue(sheetName, 17, 14, 27),
					new ExpectedCellValue(sheetName, 17, 15, 27),
					new ExpectedCellValue(sheetName, 18, 2, "384 MB PC800 ECC"),
					new ExpectedCellValue(sheetName, 18, 3, null),
					new ExpectedCellValue(sheetName, 18, 4, null),
					new ExpectedCellValue(sheetName, 18, 5, null),
					new ExpectedCellValue(sheetName, 18, 6, null),
					new ExpectedCellValue(sheetName, 18, 7, null),
					new ExpectedCellValue(sheetName, 18, 8, null),
					new ExpectedCellValue(sheetName, 18, 9, null),
					new ExpectedCellValue(sheetName, 18, 10, null),
					new ExpectedCellValue(sheetName, 18, 11, null),
					new ExpectedCellValue(sheetName, 18, 12, null),
					new ExpectedCellValue(sheetName, 18, 13, 27),
					new ExpectedCellValue(sheetName, 18, 14, 27),
					new ExpectedCellValue(sheetName, 18, 15, 27),
					new ExpectedCellValue(sheetName, 19, 2, "40GB ATA-66 IDE"),
					new ExpectedCellValue(sheetName, 19, 3, null),
					new ExpectedCellValue(sheetName, 19, 4, null),
					new ExpectedCellValue(sheetName, 19, 5, null),
					new ExpectedCellValue(sheetName, 19, 6, null),
					new ExpectedCellValue(sheetName, 19, 7, null),
					new ExpectedCellValue(sheetName, 19, 8, null),
					new ExpectedCellValue(sheetName, 19, 9, null),
					new ExpectedCellValue(sheetName, 19, 10, null),
					new ExpectedCellValue(sheetName, 19, 11, null),
					new ExpectedCellValue(sheetName, 19, 12, null),
					new ExpectedCellValue(sheetName, 19, 13, 27.9),
					new ExpectedCellValue(sheetName, 19, 14, 27.9),
					new ExpectedCellValue(sheetName, 19, 15, 27.9),
					new ExpectedCellValue(sheetName, 20, 2, "512 MB PC800 ECC"),
					new ExpectedCellValue(sheetName, 20, 3, null),
					new ExpectedCellValue(sheetName, 20, 4, null),
					new ExpectedCellValue(sheetName, 20, 5, null),
					new ExpectedCellValue(sheetName, 20, 6, null),
					new ExpectedCellValue(sheetName, 20, 7, null),
					new ExpectedCellValue(sheetName, 20, 8, null),
					new ExpectedCellValue(sheetName, 20, 9, null),
					new ExpectedCellValue(sheetName, 20, 10, null),
					new ExpectedCellValue(sheetName, 20, 11, null),
					new ExpectedCellValue(sheetName, 20, 12, null),
					new ExpectedCellValue(sheetName, 20, 13, 28.8),
					new ExpectedCellValue(sheetName, 20, 14, 28.8),
					new ExpectedCellValue(sheetName, 20, 15, 28.8),
					new ExpectedCellValue(sheetName, 21, 2, "64 MB PC800 ECC"),
					new ExpectedCellValue(sheetName, 21, 3, null),
					new ExpectedCellValue(sheetName, 21, 4, null),
					new ExpectedCellValue(sheetName, 21, 5, null),
					new ExpectedCellValue(sheetName, 21, 6, null),
					new ExpectedCellValue(sheetName, 21, 7, null),
					new ExpectedCellValue(sheetName, 21, 8, null),
					new ExpectedCellValue(sheetName, 21, 9, null),
					new ExpectedCellValue(sheetName, 21, 10, null),
					new ExpectedCellValue(sheetName, 21, 11, null),
					new ExpectedCellValue(sheetName, 21, 12, null),
					new ExpectedCellValue(sheetName, 21, 13, 9),
					new ExpectedCellValue(sheetName, 21, 14, 9),
					new ExpectedCellValue(sheetName, 21, 15, 9),
					new ExpectedCellValue(sheetName, 22, 2, "8x/4x/32x IDE CD Read-Write"),
					new ExpectedCellValue(sheetName, 22, 3, null),
					new ExpectedCellValue(sheetName, 22, 4, null),
					new ExpectedCellValue(sheetName, 22, 5, null),
					new ExpectedCellValue(sheetName, 22, 6, null),
					new ExpectedCellValue(sheetName, 22, 7, null),
					new ExpectedCellValue(sheetName, 22, 8, null),
					new ExpectedCellValue(sheetName, 22, 9, null),
					new ExpectedCellValue(sheetName, 22, 10, null),
					new ExpectedCellValue(sheetName, 22, 11, null),
					new ExpectedCellValue(sheetName, 22, 12, null),
					new ExpectedCellValue(sheetName, 22, 13, 36),
					new ExpectedCellValue(sheetName, 22, 14, 36),
					new ExpectedCellValue(sheetName, 22, 15, 36),
					new ExpectedCellValue(sheetName, 23, 2, "9GB Ultra 160/M SCSI"),
					new ExpectedCellValue(sheetName, 23, 3, null),
					new ExpectedCellValue(sheetName, 23, 4, null),
					new ExpectedCellValue(sheetName, 23, 5, null),
					new ExpectedCellValue(sheetName, 23, 6, null),
					new ExpectedCellValue(sheetName, 23, 7, null),
					new ExpectedCellValue(sheetName, 23, 8, null),
					new ExpectedCellValue(sheetName, 23, 9, null),
					new ExpectedCellValue(sheetName, 23, 10, null),
					new ExpectedCellValue(sheetName, 23, 11, null),
					new ExpectedCellValue(sheetName, 23, 12, null),
					new ExpectedCellValue(sheetName, 23, 13, 14.4),
					new ExpectedCellValue(sheetName, 23, 14, 14.4),
					new ExpectedCellValue(sheetName, 23, 15, 14.4),
					new ExpectedCellValue(sheetName, 24, 2, "Advanced Mouse"),
					new ExpectedCellValue(sheetName, 24, 3, null),
					new ExpectedCellValue(sheetName, 24, 4, null),
					new ExpectedCellValue(sheetName, 24, 5, null),
					new ExpectedCellValue(sheetName, 24, 6, null),
					new ExpectedCellValue(sheetName, 24, 7, null),
					new ExpectedCellValue(sheetName, 24, 8, null),
					new ExpectedCellValue(sheetName, 24, 9, null),
					new ExpectedCellValue(sheetName, 24, 10, null),
					new ExpectedCellValue(sheetName, 24, 11, null),
					new ExpectedCellValue(sheetName, 24, 12, null),
					new ExpectedCellValue(sheetName, 24, 13, 1.6),
					new ExpectedCellValue(sheetName, 24, 14, 1.6),
					new ExpectedCellValue(sheetName, 24, 15, 1.6),
					new ExpectedCellValue(sheetName, 25, 2, "ALBERTVILLE Whiteboard, green"),
					new ExpectedCellValue(sheetName, 25, 3, 1092.1),
					new ExpectedCellValue(sheetName, 25, 4, null),
					new ExpectedCellValue(sheetName, 25, 5, null),
					new ExpectedCellValue(sheetName, 25, 6, null),
					new ExpectedCellValue(sheetName, 25, 7, 1092.1),
					new ExpectedCellValue(sheetName, 25, 8, null),
					new ExpectedCellValue(sheetName, 25, 9, null),
					new ExpectedCellValue(sheetName, 25, 10, null),
					new ExpectedCellValue(sheetName, 25, 11, null),
					new ExpectedCellValue(sheetName, 25, 12, null),
					new ExpectedCellValue(sheetName, 25, 13, null),
					new ExpectedCellValue(sheetName, 25, 14, null),
					new ExpectedCellValue(sheetName, 25, 15, 1092.1),
					new ExpectedCellValue(sheetName, 26, 2, "AMSTERDAM Lamp"),
					new ExpectedCellValue(sheetName, 26, 3, null),
					new ExpectedCellValue(sheetName, 26, 4, null),
					new ExpectedCellValue(sheetName, 26, 5, null),
					new ExpectedCellValue(sheetName, 26, 6, null),
					new ExpectedCellValue(sheetName, 26, 7, null),
					new ExpectedCellValue(sheetName, 26, 8, null),
					new ExpectedCellValue(sheetName, 26, 9, 42.8),
					new ExpectedCellValue(sheetName, 26, 10, null),
					new ExpectedCellValue(sheetName, 26, 11, null),
					new ExpectedCellValue(sheetName, 26, 12, null),
					new ExpectedCellValue(sheetName, 26, 13, null),
					new ExpectedCellValue(sheetName, 26, 14, 42.8),
					new ExpectedCellValue(sheetName, 26, 15, 42.8),
					new ExpectedCellValue(sheetName, 27, 2, "ANTWERP Conference Table"),
					new ExpectedCellValue(sheetName, 27, 3, null),
					new ExpectedCellValue(sheetName, 27, 4, null),
					new ExpectedCellValue(sheetName, 27, 5, null),
					new ExpectedCellValue(sheetName, 27, 6, null),
					new ExpectedCellValue(sheetName, 27, 7, null),
					new ExpectedCellValue(sheetName, 27, 8, null),
					new ExpectedCellValue(sheetName, 27, 9, null),
					new ExpectedCellValue(sheetName, 27, 10, 505.4),
					new ExpectedCellValue(sheetName, 27, 11, null),
					new ExpectedCellValue(sheetName, 27, 12, null),
					new ExpectedCellValue(sheetName, 27, 13, null),
					new ExpectedCellValue(sheetName, 27, 14, 505.4),
					new ExpectedCellValue(sheetName, 27, 15, 505.4),
					new ExpectedCellValue(sheetName, 28, 2, "ATHENS Desk"),
					new ExpectedCellValue(sheetName, 28, 3, null),
					new ExpectedCellValue(sheetName, 28, 4, null),
					new ExpectedCellValue(sheetName, 28, 5, null),
					new ExpectedCellValue(sheetName, 28, 6, null),
					new ExpectedCellValue(sheetName, 28, 7, null),
					new ExpectedCellValue(sheetName, 28, 8, null),
					new ExpectedCellValue(sheetName, 28, 9, null),
					new ExpectedCellValue(sheetName, 28, 10, null),
					new ExpectedCellValue(sheetName, 28, 11, 780.7),
					new ExpectedCellValue(sheetName, 28, 12, null),
					new ExpectedCellValue(sheetName, 28, 13, null),
					new ExpectedCellValue(sheetName, 28, 14, 780.7),
					new ExpectedCellValue(sheetName, 28, 15, 780.7),
					new ExpectedCellValue(sheetName, 29, 2, "ATHENS Mobile Pedestal"),
					new ExpectedCellValue(sheetName, 29, 3, null),
					new ExpectedCellValue(sheetName, 29, 4, null),
					new ExpectedCellValue(sheetName, 29, 5, null),
					new ExpectedCellValue(sheetName, 29, 6, null),
					new ExpectedCellValue(sheetName, 29, 7, null),
					new ExpectedCellValue(sheetName, 29, 8, null),
					new ExpectedCellValue(sheetName, 29, 9, null),
					new ExpectedCellValue(sheetName, 29, 10, null),
					new ExpectedCellValue(sheetName, 29, 11, 338.2),
					new ExpectedCellValue(sheetName, 29, 12, null),
					new ExpectedCellValue(sheetName, 29, 13, null),
					new ExpectedCellValue(sheetName, 29, 14, 338.2),
					new ExpectedCellValue(sheetName, 29, 15, 338.2),
					new ExpectedCellValue(sheetName, 30, 2, "ATLANTA Whiteboard, base"),
					new ExpectedCellValue(sheetName, 30, 3, null),
					new ExpectedCellValue(sheetName, 30, 4, null),
					new ExpectedCellValue(sheetName, 30, 5, null),
					new ExpectedCellValue(sheetName, 30, 6, null),
					new ExpectedCellValue(sheetName, 30, 7, null),
					new ExpectedCellValue(sheetName, 30, 8, null),
					new ExpectedCellValue(sheetName, 30, 9, null),
					new ExpectedCellValue(sheetName, 30, 10, null),
					new ExpectedCellValue(sheetName, 30, 11, 1089.9),
					new ExpectedCellValue(sheetName, 30, 12, null),
					new ExpectedCellValue(sheetName, 30, 13, null),
					new ExpectedCellValue(sheetName, 30, 14, 1089.9),
					new ExpectedCellValue(sheetName, 30, 15, 1089.9),
					new ExpectedCellValue(sheetName, 31, 2, "Back Hub"),
					new ExpectedCellValue(sheetName, 31, 3, 12.452),
					new ExpectedCellValue(sheetName, 31, 4, null),
					new ExpectedCellValue(sheetName, 31, 5, null),
					new ExpectedCellValue(sheetName, 31, 6, null),
					new ExpectedCellValue(sheetName, 31, 7, 12.452),
					new ExpectedCellValue(sheetName, 31, 8, null),
					new ExpectedCellValue(sheetName, 31, 9, null),
					new ExpectedCellValue(sheetName, 31, 10, null),
					new ExpectedCellValue(sheetName, 31, 11, null),
					new ExpectedCellValue(sheetName, 31, 12, null),
					new ExpectedCellValue(sheetName, 31, 13, null),
					new ExpectedCellValue(sheetName, 31, 14, null),
					new ExpectedCellValue(sheetName, 31, 15, 12.452),
					new ExpectedCellValue(sheetName, 32, 2, "Back Wheel"),
					new ExpectedCellValue(sheetName, 32, 3, 129.682),
					new ExpectedCellValue(sheetName, 32, 4, null),
					new ExpectedCellValue(sheetName, 32, 5, null),
					new ExpectedCellValue(sheetName, 32, 6, null),
					new ExpectedCellValue(sheetName, 32, 7, 129.682),
					new ExpectedCellValue(sheetName, 32, 8, null),
					new ExpectedCellValue(sheetName, 32, 9, null),
					new ExpectedCellValue(sheetName, 32, 10, null),
					new ExpectedCellValue(sheetName, 32, 11, null),
					new ExpectedCellValue(sheetName, 32, 12, null),
					new ExpectedCellValue(sheetName, 32, 13, null),
					new ExpectedCellValue(sheetName, 32, 14, null),
					new ExpectedCellValue(sheetName, 32, 15, 129.682),
					new ExpectedCellValue(sheetName, 33, 2, "Base speaker unit 15\" 100W"),
					new ExpectedCellValue(sheetName, 33, 3, null),
					new ExpectedCellValue(sheetName, 33, 4, null),
					new ExpectedCellValue(sheetName, 33, 5, null),
					new ExpectedCellValue(sheetName, 33, 6, null),
					new ExpectedCellValue(sheetName, 33, 7, null),
					new ExpectedCellValue(sheetName, 33, 8, 15),
					new ExpectedCellValue(sheetName, 33, 9, null),
					new ExpectedCellValue(sheetName, 33, 10, null),
					new ExpectedCellValue(sheetName, 33, 11, null),
					new ExpectedCellValue(sheetName, 33, 12, null),
					new ExpectedCellValue(sheetName, 33, 13, null),
					new ExpectedCellValue(sheetName, 33, 14, 15),
					new ExpectedCellValue(sheetName, 33, 15, 15),
					new ExpectedCellValue(sheetName, 34, 2, "Basic Mouse"),
					new ExpectedCellValue(sheetName, 34, 3, null),
					new ExpectedCellValue(sheetName, 34, 4, null),
					new ExpectedCellValue(sheetName, 34, 5, null),
					new ExpectedCellValue(sheetName, 34, 6, null),
					new ExpectedCellValue(sheetName, 34, 7, null),
					new ExpectedCellValue(sheetName, 34, 8, null),
					new ExpectedCellValue(sheetName, 34, 9, null),
					new ExpectedCellValue(sheetName, 34, 10, null),
					new ExpectedCellValue(sheetName, 34, 11, null),
					new ExpectedCellValue(sheetName, 34, 12, null),
					new ExpectedCellValue(sheetName, 34, 13, 1.8),
					new ExpectedCellValue(sheetName, 34, 14, 1.8),
					new ExpectedCellValue(sheetName, 34, 15, 1.8),
					new ExpectedCellValue(sheetName, 35, 2, "BERLIN Guest Chair, yellow"),
					new ExpectedCellValue(sheetName, 35, 3, null),
					new ExpectedCellValue(sheetName, 35, 4, null),
					new ExpectedCellValue(sheetName, 35, 5, null),
					new ExpectedCellValue(sheetName, 35, 6, null),
					new ExpectedCellValue(sheetName, 35, 7, null),
					new ExpectedCellValue(sheetName, 35, 8, null),
					new ExpectedCellValue(sheetName, 35, 9, null),
					new ExpectedCellValue(sheetName, 35, 10, 150.3),
					new ExpectedCellValue(sheetName, 35, 11, null),
					new ExpectedCellValue(sheetName, 35, 12, null),
					new ExpectedCellValue(sheetName, 35, 13, null),
					new ExpectedCellValue(sheetName, 35, 14, 150.3),
					new ExpectedCellValue(sheetName, 35, 15, 150.3),
					new ExpectedCellValue(sheetName, 36, 2, "Bicycle"),
					new ExpectedCellValue(sheetName, 36, 3, 350.595),
					new ExpectedCellValue(sheetName, 36, 4, null),
					new ExpectedCellValue(sheetName, 36, 5, null),
					new ExpectedCellValue(sheetName, 36, 6, null),
					new ExpectedCellValue(sheetName, 36, 7, 350.595),
					new ExpectedCellValue(sheetName, 36, 8, null),
					new ExpectedCellValue(sheetName, 36, 9, null),
					new ExpectedCellValue(sheetName, 36, 10, null),
					new ExpectedCellValue(sheetName, 36, 11, null),
					new ExpectedCellValue(sheetName, 36, 12, null),
					new ExpectedCellValue(sheetName, 36, 13, null),
					new ExpectedCellValue(sheetName, 36, 14, null),
					new ExpectedCellValue(sheetName, 36, 15, 350.595),
					new ExpectedCellValue(sheetName, 37, 2, "Brake"),
					new ExpectedCellValue(sheetName, 37, 3, 9.765),
					new ExpectedCellValue(sheetName, 37, 4, null),
					new ExpectedCellValue(sheetName, 37, 5, null),
					new ExpectedCellValue(sheetName, 37, 6, null),
					new ExpectedCellValue(sheetName, 37, 7, 9.765),
					new ExpectedCellValue(sheetName, 37, 8, null),
					new ExpectedCellValue(sheetName, 37, 9, null),
					new ExpectedCellValue(sheetName, 37, 10, null),
					new ExpectedCellValue(sheetName, 37, 11, null),
					new ExpectedCellValue(sheetName, 37, 12, null),
					new ExpectedCellValue(sheetName, 37, 13, null),
					new ExpectedCellValue(sheetName, 37, 14, null),
					new ExpectedCellValue(sheetName, 37, 15, 9.765),
					new ExpectedCellValue(sheetName, 38, 2, "Cables for Loudspeakers"),
					new ExpectedCellValue(sheetName, 38, 3, null),
					new ExpectedCellValue(sheetName, 38, 4, null),
					new ExpectedCellValue(sheetName, 38, 5, null),
					new ExpectedCellValue(sheetName, 38, 6, null),
					new ExpectedCellValue(sheetName, 38, 7, null),
					new ExpectedCellValue(sheetName, 38, 8, 15),
					new ExpectedCellValue(sheetName, 38, 9, null),
					new ExpectedCellValue(sheetName, 38, 10, null),
					new ExpectedCellValue(sheetName, 38, 11, null),
					new ExpectedCellValue(sheetName, 38, 12, null),
					new ExpectedCellValue(sheetName, 38, 13, null),
					new ExpectedCellValue(sheetName, 38, 14, 15),
					new ExpectedCellValue(sheetName, 38, 15, 15),
					new ExpectedCellValue(sheetName, 39, 2, "Cabling for LS-100"),
					new ExpectedCellValue(sheetName, 39, 3, null),
					new ExpectedCellValue(sheetName, 39, 4, null),
					new ExpectedCellValue(sheetName, 39, 5, null),
					new ExpectedCellValue(sheetName, 39, 6, null),
					new ExpectedCellValue(sheetName, 39, 7, null),
					new ExpectedCellValue(sheetName, 39, 8, 15),
					new ExpectedCellValue(sheetName, 39, 9, null),
					new ExpectedCellValue(sheetName, 39, 10, null),
					new ExpectedCellValue(sheetName, 39, 11, null),
					new ExpectedCellValue(sheetName, 39, 12, null),
					new ExpectedCellValue(sheetName, 39, 13, null),
					new ExpectedCellValue(sheetName, 39, 14, 15),
					new ExpectedCellValue(sheetName, 39, 15, 15),
					new ExpectedCellValue(sheetName, 40, 2, "CALGARY Whiteboard, yellow"),
					new ExpectedCellValue(sheetName, 40, 3, 1092.1),
					new ExpectedCellValue(sheetName, 40, 4, null),
					new ExpectedCellValue(sheetName, 40, 5, null),
					new ExpectedCellValue(sheetName, 40, 6, null),
					new ExpectedCellValue(sheetName, 40, 7, 1092.1),
					new ExpectedCellValue(sheetName, 40, 8, null),
					new ExpectedCellValue(sheetName, 40, 9, null),
					new ExpectedCellValue(sheetName, 40, 10, null),
					new ExpectedCellValue(sheetName, 40, 11, null),
					new ExpectedCellValue(sheetName, 40, 12, null),
					new ExpectedCellValue(sheetName, 40, 13, null),
					new ExpectedCellValue(sheetName, 40, 14, null),
					new ExpectedCellValue(sheetName, 40, 15, 1092.1),
					new ExpectedCellValue(sheetName, 41, 2, "Chain"),
					new ExpectedCellValue(sheetName, 41, 3, null),
					new ExpectedCellValue(sheetName, 41, 4, null),
					new ExpectedCellValue(sheetName, 41, 5, null),
					new ExpectedCellValue(sheetName, 41, 6, 1.99),
					new ExpectedCellValue(sheetName, 41, 7, 1.99),
					new ExpectedCellValue(sheetName, 41, 8, null),
					new ExpectedCellValue(sheetName, 41, 9, null),
					new ExpectedCellValue(sheetName, 41, 10, null),
					new ExpectedCellValue(sheetName, 41, 11, null),
					new ExpectedCellValue(sheetName, 41, 12, null),
					new ExpectedCellValue(sheetName, 41, 13, null),
					new ExpectedCellValue(sheetName, 41, 14, null),
					new ExpectedCellValue(sheetName, 41, 15, 1.99),
					new ExpectedCellValue(sheetName, 42, 2, "Chain Assy"),
					new ExpectedCellValue(sheetName, 42, 3, 13.157),
					new ExpectedCellValue(sheetName, 42, 4, null),
					new ExpectedCellValue(sheetName, 42, 5, null),
					new ExpectedCellValue(sheetName, 42, 6, null),
					new ExpectedCellValue(sheetName, 42, 7, 13.157),
					new ExpectedCellValue(sheetName, 42, 8, null),
					new ExpectedCellValue(sheetName, 42, 9, null),
					new ExpectedCellValue(sheetName, 42, 10, null),
					new ExpectedCellValue(sheetName, 42, 11, null),
					new ExpectedCellValue(sheetName, 42, 12, null),
					new ExpectedCellValue(sheetName, 42, 13, null),
					new ExpectedCellValue(sheetName, 42, 14, null),
					new ExpectedCellValue(sheetName, 42, 15, 13.157),
					new ExpectedCellValue(sheetName, 43, 2, "CHAMONIX Base Storage Unit"),
					new ExpectedCellValue(sheetName, 43, 3, null),
					new ExpectedCellValue(sheetName, 43, 4, null),
					new ExpectedCellValue(sheetName, 43, 5, 125.6),
					new ExpectedCellValue(sheetName, 43, 6, null),
					new ExpectedCellValue(sheetName, 43, 7, 125.6),
					new ExpectedCellValue(sheetName, 43, 8, null),
					new ExpectedCellValue(sheetName, 43, 9, null),
					new ExpectedCellValue(sheetName, 43, 10, null),
					new ExpectedCellValue(sheetName, 43, 11, null),
					new ExpectedCellValue(sheetName, 43, 12, null),
					new ExpectedCellValue(sheetName, 43, 13, null),
					new ExpectedCellValue(sheetName, 43, 14, null),
					new ExpectedCellValue(sheetName, 43, 15, 125.6),
					new ExpectedCellValue(sheetName, 44, 2, "Chip 32 MB"),
					new ExpectedCellValue(sheetName, 44, 3, null),
					new ExpectedCellValue(sheetName, 44, 4, null),
					new ExpectedCellValue(sheetName, 44, 5, null),
					new ExpectedCellValue(sheetName, 44, 6, null),
					new ExpectedCellValue(sheetName, 44, 7, null),
					new ExpectedCellValue(sheetName, 44, 8, null),
					new ExpectedCellValue(sheetName, 44, 9, null),
					new ExpectedCellValue(sheetName, 44, 10, null),
					new ExpectedCellValue(sheetName, 44, 11, null),
					new ExpectedCellValue(sheetName, 44, 12, null),
					new ExpectedCellValue(sheetName, 44, 13, 4.3),
					new ExpectedCellValue(sheetName, 44, 14, 4.3),
					new ExpectedCellValue(sheetName, 44, 15, 4.3),
					new ExpectedCellValue(sheetName, 45, 2, "Computer - Basic Package"),
					new ExpectedCellValue(sheetName, 45, 3, null),
					new ExpectedCellValue(sheetName, 45, 4, null),
					new ExpectedCellValue(sheetName, 45, 5, null),
					new ExpectedCellValue(sheetName, 45, 6, null),
					new ExpectedCellValue(sheetName, 45, 7, null),
					new ExpectedCellValue(sheetName, 45, 8, null),
					new ExpectedCellValue(sheetName, 45, 9, null),
					new ExpectedCellValue(sheetName, 45, 10, null),
					new ExpectedCellValue(sheetName, 45, 11, null),
					new ExpectedCellValue(sheetName, 45, 12, null),
					new ExpectedCellValue(sheetName, 45, 13, 0),
					new ExpectedCellValue(sheetName, 45, 14, 0),
					new ExpectedCellValue(sheetName, 45, 15, 0),
					new ExpectedCellValue(sheetName, 46, 2, "Computer - Highline Package"),
					new ExpectedCellValue(sheetName, 46, 3, null),
					new ExpectedCellValue(sheetName, 46, 4, null),
					new ExpectedCellValue(sheetName, 46, 5, null),
					new ExpectedCellValue(sheetName, 46, 6, null),
					new ExpectedCellValue(sheetName, 46, 7, null),
					new ExpectedCellValue(sheetName, 46, 8, null),
					new ExpectedCellValue(sheetName, 46, 9, null),
					new ExpectedCellValue(sheetName, 46, 10, null),
					new ExpectedCellValue(sheetName, 46, 11, null),
					new ExpectedCellValue(sheetName, 46, 12, null),
					new ExpectedCellValue(sheetName, 46, 13, 0),
					new ExpectedCellValue(sheetName, 46, 14, 0),
					new ExpectedCellValue(sheetName, 46, 15, 0),
					new ExpectedCellValue(sheetName, 47, 2, "Computer - Trendy Package"),
					new ExpectedCellValue(sheetName, 47, 3, null),
					new ExpectedCellValue(sheetName, 47, 4, null),
					new ExpectedCellValue(sheetName, 47, 5, null),
					new ExpectedCellValue(sheetName, 47, 6, null),
					new ExpectedCellValue(sheetName, 47, 7, null),
					new ExpectedCellValue(sheetName, 47, 8, null),
					new ExpectedCellValue(sheetName, 47, 9, null),
					new ExpectedCellValue(sheetName, 47, 10, null),
					new ExpectedCellValue(sheetName, 47, 11, null),
					new ExpectedCellValue(sheetName, 47, 12, null),
					new ExpectedCellValue(sheetName, 47, 13, 0),
					new ExpectedCellValue(sheetName, 47, 14, 0),
					new ExpectedCellValue(sheetName, 47, 15, 0),
					new ExpectedCellValue(sheetName, 48, 2, "Computer - TURBO Package"),
					new ExpectedCellValue(sheetName, 48, 3, null),
					new ExpectedCellValue(sheetName, 48, 4, null),
					new ExpectedCellValue(sheetName, 48, 5, null),
					new ExpectedCellValue(sheetName, 48, 6, null),
					new ExpectedCellValue(sheetName, 48, 7, null),
					new ExpectedCellValue(sheetName, 48, 8, null),
					new ExpectedCellValue(sheetName, 48, 9, null),
					new ExpectedCellValue(sheetName, 48, 10, null),
					new ExpectedCellValue(sheetName, 48, 11, null),
					new ExpectedCellValue(sheetName, 48, 12, null),
					new ExpectedCellValue(sheetName, 48, 13, 0),
					new ExpectedCellValue(sheetName, 48, 14, 0),
					new ExpectedCellValue(sheetName, 48, 15, 0),
					new ExpectedCellValue(sheetName, 49, 2, "Computer III 533 MHz"),
					new ExpectedCellValue(sheetName, 49, 3, null),
					new ExpectedCellValue(sheetName, 49, 4, null),
					new ExpectedCellValue(sheetName, 49, 5, null),
					new ExpectedCellValue(sheetName, 49, 6, null),
					new ExpectedCellValue(sheetName, 49, 7, null),
					new ExpectedCellValue(sheetName, 49, 8, null),
					new ExpectedCellValue(sheetName, 49, 9, null),
					new ExpectedCellValue(sheetName, 49, 10, null),
					new ExpectedCellValue(sheetName, 49, 11, null),
					new ExpectedCellValue(sheetName, 49, 12, null),
					new ExpectedCellValue(sheetName, 49, 13, 9),
					new ExpectedCellValue(sheetName, 49, 14, 9),
					new ExpectedCellValue(sheetName, 49, 15, 9),
					new ExpectedCellValue(sheetName, 50, 2, "Computer III 600 MHz"),
					new ExpectedCellValue(sheetName, 50, 3, null),
					new ExpectedCellValue(sheetName, 50, 4, null),
					new ExpectedCellValue(sheetName, 50, 5, null),
					new ExpectedCellValue(sheetName, 50, 6, null),
					new ExpectedCellValue(sheetName, 50, 7, null),
					new ExpectedCellValue(sheetName, 50, 8, null),
					new ExpectedCellValue(sheetName, 50, 9, null),
					new ExpectedCellValue(sheetName, 50, 10, null),
					new ExpectedCellValue(sheetName, 50, 11, null),
					new ExpectedCellValue(sheetName, 50, 12, null),
					new ExpectedCellValue(sheetName, 50, 13, 10.8),
					new ExpectedCellValue(sheetName, 50, 14, 10.8),
					new ExpectedCellValue(sheetName, 50, 15, 10.8),
					new ExpectedCellValue(sheetName, 51, 2, "Computer III 733 MHz"),
					new ExpectedCellValue(sheetName, 51, 3, null),
					new ExpectedCellValue(sheetName, 51, 4, null),
					new ExpectedCellValue(sheetName, 51, 5, null),
					new ExpectedCellValue(sheetName, 51, 6, null),
					new ExpectedCellValue(sheetName, 51, 7, null),
					new ExpectedCellValue(sheetName, 51, 8, null),
					new ExpectedCellValue(sheetName, 51, 9, null),
					new ExpectedCellValue(sheetName, 51, 10, null),
					new ExpectedCellValue(sheetName, 51, 11, null),
					new ExpectedCellValue(sheetName, 51, 12, null),
					new ExpectedCellValue(sheetName, 51, 13, 12.6),
					new ExpectedCellValue(sheetName, 51, 14, 12.6),
					new ExpectedCellValue(sheetName, 51, 15, 12.6),
					new ExpectedCellValue(sheetName, 52, 2, "Computer III 800 MHz"),
					new ExpectedCellValue(sheetName, 52, 3, null),
					new ExpectedCellValue(sheetName, 52, 4, null),
					new ExpectedCellValue(sheetName, 52, 5, null),
					new ExpectedCellValue(sheetName, 52, 6, null),
					new ExpectedCellValue(sheetName, 52, 7, null),
					new ExpectedCellValue(sheetName, 52, 8, null),
					new ExpectedCellValue(sheetName, 52, 9, null),
					new ExpectedCellValue(sheetName, 52, 10, null),
					new ExpectedCellValue(sheetName, 52, 11, null),
					new ExpectedCellValue(sheetName, 52, 12, null),
					new ExpectedCellValue(sheetName, 52, 13, 14.4),
					new ExpectedCellValue(sheetName, 52, 14, 14.4),
					new ExpectedCellValue(sheetName, 52, 15, 14.4),
					new ExpectedCellValue(sheetName, 53, 2, "Computer III 866 MHz"),
					new ExpectedCellValue(sheetName, 53, 3, null),
					new ExpectedCellValue(sheetName, 53, 4, null),
					new ExpectedCellValue(sheetName, 53, 5, null),
					new ExpectedCellValue(sheetName, 53, 6, null),
					new ExpectedCellValue(sheetName, 53, 7, null),
					new ExpectedCellValue(sheetName, 53, 8, null),
					new ExpectedCellValue(sheetName, 53, 9, null),
					new ExpectedCellValue(sheetName, 53, 10, null),
					new ExpectedCellValue(sheetName, 53, 11, null),
					new ExpectedCellValue(sheetName, 53, 12, null),
					new ExpectedCellValue(sheetName, 53, 13, 16.2),
					new ExpectedCellValue(sheetName, 53, 14, 16.2),
					new ExpectedCellValue(sheetName, 53, 15, 16.2),
					new ExpectedCellValue(sheetName, 54, 2, "CONTOSO Conference System"),
					new ExpectedCellValue(sheetName, 54, 3, 5422.7),
					new ExpectedCellValue(sheetName, 54, 4, null),
					new ExpectedCellValue(sheetName, 54, 5, null),
					new ExpectedCellValue(sheetName, 54, 6, null),
					new ExpectedCellValue(sheetName, 54, 7, 5422.7),
					new ExpectedCellValue(sheetName, 54, 8, null),
					new ExpectedCellValue(sheetName, 54, 9, null),
					new ExpectedCellValue(sheetName, 54, 10, null),
					new ExpectedCellValue(sheetName, 54, 11, null),
					new ExpectedCellValue(sheetName, 54, 12, null),
					new ExpectedCellValue(sheetName, 54, 13, null),
					new ExpectedCellValue(sheetName, 54, 14, null),
					new ExpectedCellValue(sheetName, 54, 15, 5422.7),
					new ExpectedCellValue(sheetName, 55, 2, "CONTOSO Office System"),
					new ExpectedCellValue(sheetName, 55, 3, 1919.7),
					new ExpectedCellValue(sheetName, 55, 4, null),
					new ExpectedCellValue(sheetName, 55, 5, null),
					new ExpectedCellValue(sheetName, 55, 6, null),
					new ExpectedCellValue(sheetName, 55, 7, 1919.7),
					new ExpectedCellValue(sheetName, 55, 8, null),
					new ExpectedCellValue(sheetName, 55, 9, null),
					new ExpectedCellValue(sheetName, 55, 10, null),
					new ExpectedCellValue(sheetName, 55, 11, null),
					new ExpectedCellValue(sheetName, 55, 12, null),
					new ExpectedCellValue(sheetName, 55, 13, null),
					new ExpectedCellValue(sheetName, 55, 14, null),
					new ExpectedCellValue(sheetName, 55, 15, 1919.7),
					new ExpectedCellValue(sheetName, 56, 2, "CONTOSO Storage System"),
					new ExpectedCellValue(sheetName, 56, 3, 945.9),
					new ExpectedCellValue(sheetName, 56, 4, null),
					new ExpectedCellValue(sheetName, 56, 5, null),
					new ExpectedCellValue(sheetName, 56, 6, null),
					new ExpectedCellValue(sheetName, 56, 7, 945.9),
					new ExpectedCellValue(sheetName, 56, 8, null),
					new ExpectedCellValue(sheetName, 56, 9, null),
					new ExpectedCellValue(sheetName, 56, 10, null),
					new ExpectedCellValue(sheetName, 56, 11, null),
					new ExpectedCellValue(sheetName, 56, 12, null),
					new ExpectedCellValue(sheetName, 56, 13, null),
					new ExpectedCellValue(sheetName, 56, 14, null),
					new ExpectedCellValue(sheetName, 56, 15, 945.9),
					new ExpectedCellValue(sheetName, 57, 2, "Drive250"),
					new ExpectedCellValue(sheetName, 57, 3, null),
					new ExpectedCellValue(sheetName, 57, 4, null),
					new ExpectedCellValue(sheetName, 57, 5, null),
					new ExpectedCellValue(sheetName, 57, 6, null),
					new ExpectedCellValue(sheetName, 57, 7, null),
					new ExpectedCellValue(sheetName, 57, 8, null),
					new ExpectedCellValue(sheetName, 57, 9, null),
					new ExpectedCellValue(sheetName, 57, 10, null),
					new ExpectedCellValue(sheetName, 57, 11, null),
					new ExpectedCellValue(sheetName, 57, 12, null),
					new ExpectedCellValue(sheetName, 57, 13, 7.2),
					new ExpectedCellValue(sheetName, 57, 14, 7.2),
					new ExpectedCellValue(sheetName, 57, 15, 7.2),
					new ExpectedCellValue(sheetName, 58, 2, "Enterprise Computer 667 MHz"),
					new ExpectedCellValue(sheetName, 58, 3, null),
					new ExpectedCellValue(sheetName, 58, 4, null),
					new ExpectedCellValue(sheetName, 58, 5, null),
					new ExpectedCellValue(sheetName, 58, 6, null),
					new ExpectedCellValue(sheetName, 58, 7, null),
					new ExpectedCellValue(sheetName, 58, 8, null),
					new ExpectedCellValue(sheetName, 58, 9, null),
					new ExpectedCellValue(sheetName, 58, 10, null),
					new ExpectedCellValue(sheetName, 58, 11, null),
					new ExpectedCellValue(sheetName, 58, 12, null),
					new ExpectedCellValue(sheetName, 58, 13, 198),
					new ExpectedCellValue(sheetName, 58, 14, 198),
					new ExpectedCellValue(sheetName, 58, 15, 198),
					new ExpectedCellValue(sheetName, 59, 2, "Ethernet Cable"),
					new ExpectedCellValue(sheetName, 59, 3, null),
					new ExpectedCellValue(sheetName, 59, 4, null),
					new ExpectedCellValue(sheetName, 59, 5, null),
					new ExpectedCellValue(sheetName, 59, 6, null),
					new ExpectedCellValue(sheetName, 59, 7, null),
					new ExpectedCellValue(sheetName, 59, 8, null),
					new ExpectedCellValue(sheetName, 59, 9, 0.7),
					new ExpectedCellValue(sheetName, 59, 10, null),
					new ExpectedCellValue(sheetName, 59, 11, null),
					new ExpectedCellValue(sheetName, 59, 12, null),
					new ExpectedCellValue(sheetName, 59, 13, 0.2),
					new ExpectedCellValue(sheetName, 59, 14, 0.9),
					new ExpectedCellValue(sheetName, 59, 15, 0.9),
					new ExpectedCellValue(sheetName, 60, 2, "Frequency filter for LS-100"),
					new ExpectedCellValue(sheetName, 60, 3, null),
					new ExpectedCellValue(sheetName, 60, 4, null),
					new ExpectedCellValue(sheetName, 60, 5, null),
					new ExpectedCellValue(sheetName, 60, 6, null),
					new ExpectedCellValue(sheetName, 60, 7, null),
					new ExpectedCellValue(sheetName, 60, 8, 15),
					new ExpectedCellValue(sheetName, 60, 9, null),
					new ExpectedCellValue(sheetName, 60, 10, null),
					new ExpectedCellValue(sheetName, 60, 11, null),
					new ExpectedCellValue(sheetName, 60, 12, null),
					new ExpectedCellValue(sheetName, 60, 13, null),
					new ExpectedCellValue(sheetName, 60, 14, 15),
					new ExpectedCellValue(sheetName, 60, 15, 15),
					new ExpectedCellValue(sheetName, 61, 2, "Front Hub"),
					new ExpectedCellValue(sheetName, 61, 3, 12.441),
					new ExpectedCellValue(sheetName, 61, 4, null),
					new ExpectedCellValue(sheetName, 61, 5, null),
					new ExpectedCellValue(sheetName, 61, 6, null),
					new ExpectedCellValue(sheetName, 61, 7, 12.441),
					new ExpectedCellValue(sheetName, 61, 8, null),
					new ExpectedCellValue(sheetName, 61, 9, null),
					new ExpectedCellValue(sheetName, 61, 10, null),
					new ExpectedCellValue(sheetName, 61, 11, null),
					new ExpectedCellValue(sheetName, 61, 12, null),
					new ExpectedCellValue(sheetName, 61, 13, null),
					new ExpectedCellValue(sheetName, 61, 14, null),
					new ExpectedCellValue(sheetName, 61, 15, 12.441),
					new ExpectedCellValue(sheetName, 62, 2, "Front Wheel"),
					new ExpectedCellValue(sheetName, 62, 3, null),
					new ExpectedCellValue(sheetName, 62, 4, null),
					new ExpectedCellValue(sheetName, 62, 5, 129.671),
					new ExpectedCellValue(sheetName, 62, 6, null),
					new ExpectedCellValue(sheetName, 62, 7, 129.671),
					new ExpectedCellValue(sheetName, 62, 8, null),
					new ExpectedCellValue(sheetName, 62, 9, null),
					new ExpectedCellValue(sheetName, 62, 10, null),
					new ExpectedCellValue(sheetName, 62, 11, null),
					new ExpectedCellValue(sheetName, 62, 12, null),
					new ExpectedCellValue(sheetName, 62, 13, null),
					new ExpectedCellValue(sheetName, 62, 14, null),
					new ExpectedCellValue(sheetName, 62, 15, 129.671),
					new ExpectedCellValue(sheetName, 63, 2, "Graphic Card 9400"),
					new ExpectedCellValue(sheetName, 63, 3, null),
					new ExpectedCellValue(sheetName, 63, 4, null),
					new ExpectedCellValue(sheetName, 63, 5, null),
					new ExpectedCellValue(sheetName, 63, 6, null),
					new ExpectedCellValue(sheetName, 63, 7, null),
					new ExpectedCellValue(sheetName, 63, 8, null),
					new ExpectedCellValue(sheetName, 63, 9, null),
					new ExpectedCellValue(sheetName, 63, 10, null),
					new ExpectedCellValue(sheetName, 63, 11, null),
					new ExpectedCellValue(sheetName, 63, 12, null),
					new ExpectedCellValue(sheetName, 63, 13, 5.4),
					new ExpectedCellValue(sheetName, 63, 14, 5.4),
					new ExpectedCellValue(sheetName, 63, 15, 5.4),
					new ExpectedCellValue(sheetName, 64, 2, "GRAPHIC PROGRAM"),
					new ExpectedCellValue(sheetName, 64, 3, null),
					new ExpectedCellValue(sheetName, 64, 4, null),
					new ExpectedCellValue(sheetName, 64, 5, null),
					new ExpectedCellValue(sheetName, 64, 6, null),
					new ExpectedCellValue(sheetName, 64, 7, null),
					new ExpectedCellValue(sheetName, 64, 8, null),
					new ExpectedCellValue(sheetName, 64, 9, null),
					new ExpectedCellValue(sheetName, 64, 10, null),
					new ExpectedCellValue(sheetName, 64, 11, null),
					new ExpectedCellValue(sheetName, 64, 12, null),
					new ExpectedCellValue(sheetName, 64, 13, 3.6),
					new ExpectedCellValue(sheetName, 64, 14, 3.6),
					new ExpectedCellValue(sheetName, 64, 15, 3.6),
					new ExpectedCellValue(sheetName, 65, 2, "GRENOBLE Whiteboard, red"),
					new ExpectedCellValue(sheetName, 65, 3, 1092.1),
					new ExpectedCellValue(sheetName, 65, 4, null),
					new ExpectedCellValue(sheetName, 65, 5, null),
					new ExpectedCellValue(sheetName, 65, 6, null),
					new ExpectedCellValue(sheetName, 65, 7, 1092.1),
					new ExpectedCellValue(sheetName, 65, 8, null),
					new ExpectedCellValue(sheetName, 65, 9, null),
					new ExpectedCellValue(sheetName, 65, 10, null),
					new ExpectedCellValue(sheetName, 65, 11, null),
					new ExpectedCellValue(sheetName, 65, 12, null),
					new ExpectedCellValue(sheetName, 65, 13, null),
					new ExpectedCellValue(sheetName, 65, 14, null),
					new ExpectedCellValue(sheetName, 65, 15, 1092.1),
					new ExpectedCellValue(sheetName, 66, 2, "Hand rear wheel Brake"),
					new ExpectedCellValue(sheetName, 66, 3, null),
					new ExpectedCellValue(sheetName, 66, 4, null),
					new ExpectedCellValue(sheetName, 66, 5, null),
					new ExpectedCellValue(sheetName, 66, 6, 4.5),
					new ExpectedCellValue(sheetName, 66, 7, 4.5),
					new ExpectedCellValue(sheetName, 66, 8, null),
					new ExpectedCellValue(sheetName, 66, 9, null),
					new ExpectedCellValue(sheetName, 66, 10, null),
					new ExpectedCellValue(sheetName, 66, 11, null),
					new ExpectedCellValue(sheetName, 66, 12, null),
					new ExpectedCellValue(sheetName, 66, 13, null),
					new ExpectedCellValue(sheetName, 66, 14, null),
					new ExpectedCellValue(sheetName, 66, 15, 4.5),
					new ExpectedCellValue(sheetName, 67, 2, "Hard Disk Drive"),
					new ExpectedCellValue(sheetName, 67, 3, null),
					new ExpectedCellValue(sheetName, 67, 4, null),
					new ExpectedCellValue(sheetName, 67, 5, null),
					new ExpectedCellValue(sheetName, 67, 6, null),
					new ExpectedCellValue(sheetName, 67, 7, null),
					new ExpectedCellValue(sheetName, 67, 8, null),
					new ExpectedCellValue(sheetName, 67, 9, 28.8),
					new ExpectedCellValue(sheetName, 67, 10, null),
					new ExpectedCellValue(sheetName, 67, 11, null),
					new ExpectedCellValue(sheetName, 67, 12, null),
					new ExpectedCellValue(sheetName, 67, 13, 3.6),
					new ExpectedCellValue(sheetName, 67, 14, 32.4),
					new ExpectedCellValue(sheetName, 67, 15, 32.4),
					new ExpectedCellValue(sheetName, 68, 2, "Housing LS-100,Oakwood 120 lts"),
					new ExpectedCellValue(sheetName, 68, 3, null),
					new ExpectedCellValue(sheetName, 68, 4, null),
					new ExpectedCellValue(sheetName, 68, 5, null),
					new ExpectedCellValue(sheetName, 68, 6, null),
					new ExpectedCellValue(sheetName, 68, 7, null),
					new ExpectedCellValue(sheetName, 68, 8, 15),
					new ExpectedCellValue(sheetName, 68, 9, null),
					new ExpectedCellValue(sheetName, 68, 10, null),
					new ExpectedCellValue(sheetName, 68, 11, null),
					new ExpectedCellValue(sheetName, 68, 12, null),
					new ExpectedCellValue(sheetName, 68, 13, null),
					new ExpectedCellValue(sheetName, 68, 14, 15),
					new ExpectedCellValue(sheetName, 68, 15, 15),
					new ExpectedCellValue(sheetName, 69, 2, "INNSBRUCK Storage Unit/G.Door"),
					new ExpectedCellValue(sheetName, 69, 3, 264),
					new ExpectedCellValue(sheetName, 69, 4, null),
					new ExpectedCellValue(sheetName, 69, 5, null),
					new ExpectedCellValue(sheetName, 69, 6, null),
					new ExpectedCellValue(sheetName, 69, 7, 264),
					new ExpectedCellValue(sheetName, 69, 8, null),
					new ExpectedCellValue(sheetName, 69, 9, null),
					new ExpectedCellValue(sheetName, 69, 10, null),
					new ExpectedCellValue(sheetName, 69, 11, null),
					new ExpectedCellValue(sheetName, 69, 12, null),
					new ExpectedCellValue(sheetName, 69, 13, null),
					new ExpectedCellValue(sheetName, 69, 14, null),
					new ExpectedCellValue(sheetName, 69, 15, 264),
					new ExpectedCellValue(sheetName, 70, 2, "INNSBRUCK Storage Unit/W.Door"),
					new ExpectedCellValue(sheetName, 70, 3, 232),
					new ExpectedCellValue(sheetName, 70, 4, null),
					new ExpectedCellValue(sheetName, 70, 5, null),
					new ExpectedCellValue(sheetName, 70, 6, null),
					new ExpectedCellValue(sheetName, 70, 7, 232),
					new ExpectedCellValue(sheetName, 70, 8, null),
					new ExpectedCellValue(sheetName, 70, 9, null),
					new ExpectedCellValue(sheetName, 70, 10, null),
					new ExpectedCellValue(sheetName, 70, 11, null),
					new ExpectedCellValue(sheetName, 70, 12, null),
					new ExpectedCellValue(sheetName, 70, 13, null),
					new ExpectedCellValue(sheetName, 70, 14, null),
					new ExpectedCellValue(sheetName, 70, 15, 232),
					new ExpectedCellValue(sheetName, 71, 2, "LONDON Swivel Chair, blue"),
					new ExpectedCellValue(sheetName, 71, 3, null),
					new ExpectedCellValue(sheetName, 71, 4, null),
					new ExpectedCellValue(sheetName, 71, 5, null),
					new ExpectedCellValue(sheetName, 71, 6, null),
					new ExpectedCellValue(sheetName, 71, 7, null),
					new ExpectedCellValue(sheetName, 71, 8, null),
					new ExpectedCellValue(sheetName, 71, 9, null),
					new ExpectedCellValue(sheetName, 71, 10, null),
					new ExpectedCellValue(sheetName, 71, 11, 148.1),
					new ExpectedCellValue(sheetName, 71, 12, null),
					new ExpectedCellValue(sheetName, 71, 13, null),
					new ExpectedCellValue(sheetName, 71, 14, 148.1),
					new ExpectedCellValue(sheetName, 71, 15, 148.1),
					new ExpectedCellValue(sheetName, 72, 2, "Loudspeaker 100W OakwoodDeluxe"),
					new ExpectedCellValue(sheetName, 72, 3, null),
					new ExpectedCellValue(sheetName, 72, 4, null),
					new ExpectedCellValue(sheetName, 72, 5, null),
					new ExpectedCellValue(sheetName, 72, 6, null),
					new ExpectedCellValue(sheetName, 72, 7, null),
					new ExpectedCellValue(sheetName, 72, 8, 15),
					new ExpectedCellValue(sheetName, 72, 9, null),
					new ExpectedCellValue(sheetName, 72, 10, null),
					new ExpectedCellValue(sheetName, 72, 11, null),
					new ExpectedCellValue(sheetName, 72, 12, null),
					new ExpectedCellValue(sheetName, 72, 13, null),
					new ExpectedCellValue(sheetName, 72, 14, 15),
					new ExpectedCellValue(sheetName, 72, 15, 15),
					new ExpectedCellValue(sheetName, 73, 2, "Loudspeaker, Black, 120W"),
					new ExpectedCellValue(sheetName, 73, 3, null),
					new ExpectedCellValue(sheetName, 73, 4, null),
					new ExpectedCellValue(sheetName, 73, 5, null),
					new ExpectedCellValue(sheetName, 73, 6, null),
					new ExpectedCellValue(sheetName, 73, 7, null),
					new ExpectedCellValue(sheetName, 73, 8, 45),
					new ExpectedCellValue(sheetName, 73, 9, null),
					new ExpectedCellValue(sheetName, 73, 10, null),
					new ExpectedCellValue(sheetName, 73, 11, null),
					new ExpectedCellValue(sheetName, 73, 12, null),
					new ExpectedCellValue(sheetName, 73, 13, null),
					new ExpectedCellValue(sheetName, 73, 14, 45),
					new ExpectedCellValue(sheetName, 73, 15, 45),
					new ExpectedCellValue(sheetName, 74, 2, "Loudspeaker, Cherry, 150W"),
					new ExpectedCellValue(sheetName, 74, 3, null),
					new ExpectedCellValue(sheetName, 74, 4, null),
					new ExpectedCellValue(sheetName, 74, 5, null),
					new ExpectedCellValue(sheetName, 74, 6, null),
					new ExpectedCellValue(sheetName, 74, 7, null),
					new ExpectedCellValue(sheetName, 74, 8, 72),
					new ExpectedCellValue(sheetName, 74, 9, null),
					new ExpectedCellValue(sheetName, 74, 10, null),
					new ExpectedCellValue(sheetName, 74, 11, null),
					new ExpectedCellValue(sheetName, 74, 12, null),
					new ExpectedCellValue(sheetName, 74, 13, null),
					new ExpectedCellValue(sheetName, 74, 14, 72),
					new ExpectedCellValue(sheetName, 74, 15, 72),
					new ExpectedCellValue(sheetName, 75, 2, "Loudspeaker, Cherry, 75W"),
					new ExpectedCellValue(sheetName, 75, 3, null),
					new ExpectedCellValue(sheetName, 75, 4, null),
					new ExpectedCellValue(sheetName, 75, 5, null),
					new ExpectedCellValue(sheetName, 75, 6, null),
					new ExpectedCellValue(sheetName, 75, 7, null),
					new ExpectedCellValue(sheetName, 75, 8, 36),
					new ExpectedCellValue(sheetName, 75, 9, null),
					new ExpectedCellValue(sheetName, 75, 10, null),
					new ExpectedCellValue(sheetName, 75, 11, null),
					new ExpectedCellValue(sheetName, 75, 12, null),
					new ExpectedCellValue(sheetName, 75, 13, null),
					new ExpectedCellValue(sheetName, 75, 14, 36),
					new ExpectedCellValue(sheetName, 75, 15, 36),
					new ExpectedCellValue(sheetName, 76, 2, "Loudspeaker, Walnut, 80W"),
					new ExpectedCellValue(sheetName, 76, 3, null),
					new ExpectedCellValue(sheetName, 76, 4, null),
					new ExpectedCellValue(sheetName, 76, 5, null),
					new ExpectedCellValue(sheetName, 76, 6, null),
					new ExpectedCellValue(sheetName, 76, 7, null),
					new ExpectedCellValue(sheetName, 76, 8, 36),
					new ExpectedCellValue(sheetName, 76, 9, null),
					new ExpectedCellValue(sheetName, 76, 10, null),
					new ExpectedCellValue(sheetName, 76, 11, null),
					new ExpectedCellValue(sheetName, 76, 12, null),
					new ExpectedCellValue(sheetName, 76, 13, null),
					new ExpectedCellValue(sheetName, 76, 14, 36),
					new ExpectedCellValue(sheetName, 76, 15, 36),
					new ExpectedCellValue(sheetName, 77, 2, "Loudspeakers, White for PC"),
					new ExpectedCellValue(sheetName, 77, 3, null),
					new ExpectedCellValue(sheetName, 77, 4, null),
					new ExpectedCellValue(sheetName, 77, 5, null),
					new ExpectedCellValue(sheetName, 77, 6, null),
					new ExpectedCellValue(sheetName, 77, 7, null),
					new ExpectedCellValue(sheetName, 77, 8, 25),
					new ExpectedCellValue(sheetName, 77, 9, null),
					new ExpectedCellValue(sheetName, 77, 10, null),
					new ExpectedCellValue(sheetName, 77, 11, null),
					new ExpectedCellValue(sheetName, 77, 12, null),
					new ExpectedCellValue(sheetName, 77, 13, null),
					new ExpectedCellValue(sheetName, 77, 14, 25),
					new ExpectedCellValue(sheetName, 77, 15, 25),
					new ExpectedCellValue(sheetName, 78, 2, "Manual for Loudspeakers"),
					new ExpectedCellValue(sheetName, 78, 3, null),
					new ExpectedCellValue(sheetName, 78, 4, null),
					new ExpectedCellValue(sheetName, 78, 5, null),
					new ExpectedCellValue(sheetName, 78, 6, null),
					new ExpectedCellValue(sheetName, 78, 7, null),
					new ExpectedCellValue(sheetName, 78, 8, 12),
					new ExpectedCellValue(sheetName, 78, 9, null),
					new ExpectedCellValue(sheetName, 78, 10, null),
					new ExpectedCellValue(sheetName, 78, 11, null),
					new ExpectedCellValue(sheetName, 78, 12, null),
					new ExpectedCellValue(sheetName, 78, 13, null),
					new ExpectedCellValue(sheetName, 78, 14, 12),
					new ExpectedCellValue(sheetName, 78, 15, 12),
					new ExpectedCellValue(sheetName, 79, 2, "MEXICO Swivel Chair, black"),
					new ExpectedCellValue(sheetName, 79, 3, null),
					new ExpectedCellValue(sheetName, 79, 4, null),
					new ExpectedCellValue(sheetName, 79, 5, null),
					new ExpectedCellValue(sheetName, 79, 6, null),
					new ExpectedCellValue(sheetName, 79, 7, null),
					new ExpectedCellValue(sheetName, 79, 8, null),
					new ExpectedCellValue(sheetName, 79, 9, null),
					new ExpectedCellValue(sheetName, 79, 10, null),
					new ExpectedCellValue(sheetName, 79, 11, 148.1),
					new ExpectedCellValue(sheetName, 79, 12, null),
					new ExpectedCellValue(sheetName, 79, 13, null),
					new ExpectedCellValue(sheetName, 79, 14, 148.1),
					new ExpectedCellValue(sheetName, 79, 15, 148.1),
					new ExpectedCellValue(sheetName, 80, 2, "Microsoft Intellimouse"),
					new ExpectedCellValue(sheetName, 80, 3, null),
					new ExpectedCellValue(sheetName, 80, 4, null),
					new ExpectedCellValue(sheetName, 80, 5, null),
					new ExpectedCellValue(sheetName, 80, 6, null),
					new ExpectedCellValue(sheetName, 80, 7, null),
					new ExpectedCellValue(sheetName, 80, 8, null),
					new ExpectedCellValue(sheetName, 80, 9, 3.1),
					new ExpectedCellValue(sheetName, 80, 10, null),
					new ExpectedCellValue(sheetName, 80, 11, null),
					new ExpectedCellValue(sheetName, 80, 12, null),
					new ExpectedCellValue(sheetName, 80, 13, null),
					new ExpectedCellValue(sheetName, 80, 14, 3.1),
					new ExpectedCellValue(sheetName, 80, 15, 3.1),
					new ExpectedCellValue(sheetName, 81, 2, "Middletone speaker unit 8\"100W"),
					new ExpectedCellValue(sheetName, 81, 3, null),
					new ExpectedCellValue(sheetName, 81, 4, null),
					new ExpectedCellValue(sheetName, 81, 5, null),
					new ExpectedCellValue(sheetName, 81, 6, null),
					new ExpectedCellValue(sheetName, 81, 7, null),
					new ExpectedCellValue(sheetName, 81, 8, 15),
					new ExpectedCellValue(sheetName, 81, 9, null),
					new ExpectedCellValue(sheetName, 81, 10, null),
					new ExpectedCellValue(sheetName, 81, 11, null),
					new ExpectedCellValue(sheetName, 81, 12, null),
					new ExpectedCellValue(sheetName, 81, 13, null),
					new ExpectedCellValue(sheetName, 81, 14, 15),
					new ExpectedCellValue(sheetName, 81, 15, 15),
					new ExpectedCellValue(sheetName, 82, 2, "MOSCOW Swivel Chair, red"),
					new ExpectedCellValue(sheetName, 82, 3, null),
					new ExpectedCellValue(sheetName, 82, 4, null),
					new ExpectedCellValue(sheetName, 82, 5, null),
					new ExpectedCellValue(sheetName, 82, 6, null),
					new ExpectedCellValue(sheetName, 82, 7, null),
					new ExpectedCellValue(sheetName, 82, 8, null),
					new ExpectedCellValue(sheetName, 82, 9, null),
					new ExpectedCellValue(sheetName, 82, 10, null),
					new ExpectedCellValue(sheetName, 82, 11, 148.1),
					new ExpectedCellValue(sheetName, 82, 12, null),
					new ExpectedCellValue(sheetName, 82, 13, null),
					new ExpectedCellValue(sheetName, 82, 14, 148.1),
					new ExpectedCellValue(sheetName, 82, 15, 148.1),
					new ExpectedCellValue(sheetName, 83, 2, "MUNICH Swivel Chair, yellow"),
					new ExpectedCellValue(sheetName, 83, 3, null),
					new ExpectedCellValue(sheetName, 83, 4, null),
					new ExpectedCellValue(sheetName, 83, 5, null),
					new ExpectedCellValue(sheetName, 83, 6, null),
					new ExpectedCellValue(sheetName, 83, 7, null),
					new ExpectedCellValue(sheetName, 83, 8, null),
					new ExpectedCellValue(sheetName, 83, 9, null),
					new ExpectedCellValue(sheetName, 83, 10, null),
					new ExpectedCellValue(sheetName, 83, 11, 148.1),
					new ExpectedCellValue(sheetName, 83, 12, null),
					new ExpectedCellValue(sheetName, 83, 13, null),
					new ExpectedCellValue(sheetName, 83, 14, 148.1),
					new ExpectedCellValue(sheetName, 83, 15, 148.1),
					new ExpectedCellValue(sheetName, 84, 2, "OSLO Storage Unit/Shelf"),
					new ExpectedCellValue(sheetName, 84, 3, 144),
					new ExpectedCellValue(sheetName, 84, 4, null),
					new ExpectedCellValue(sheetName, 84, 5, null),
					new ExpectedCellValue(sheetName, 84, 6, null),
					new ExpectedCellValue(sheetName, 84, 7, 144),
					new ExpectedCellValue(sheetName, 84, 8, null),
					new ExpectedCellValue(sheetName, 84, 9, null),
					new ExpectedCellValue(sheetName, 84, 10, null),
					new ExpectedCellValue(sheetName, 84, 11, null),
					new ExpectedCellValue(sheetName, 84, 12, null),
					new ExpectedCellValue(sheetName, 84, 13, null),
					new ExpectedCellValue(sheetName, 84, 14, null),
					new ExpectedCellValue(sheetName, 84, 15, 144),
					new ExpectedCellValue(sheetName, 85, 2, "PARIS Guest Chair, black"),
					new ExpectedCellValue(sheetName, 85, 3, null),
					new ExpectedCellValue(sheetName, 85, 4, null),
					new ExpectedCellValue(sheetName, 85, 5, null),
					new ExpectedCellValue(sheetName, 85, 6, null),
					new ExpectedCellValue(sheetName, 85, 7, null),
					new ExpectedCellValue(sheetName, 85, 8, null),
					new ExpectedCellValue(sheetName, 85, 9, null),
					new ExpectedCellValue(sheetName, 85, 10, 150.3),
					new ExpectedCellValue(sheetName, 85, 11, null),
					new ExpectedCellValue(sheetName, 85, 12, null),
					new ExpectedCellValue(sheetName, 85, 13, null),
					new ExpectedCellValue(sheetName, 85, 14, 150.3),
					new ExpectedCellValue(sheetName, 85, 15, 150.3),
					new ExpectedCellValue(sheetName, 86, 2, "Performance Keyboard"),
					new ExpectedCellValue(sheetName, 86, 3, null),
					new ExpectedCellValue(sheetName, 86, 4, null),
					new ExpectedCellValue(sheetName, 86, 5, null),
					new ExpectedCellValue(sheetName, 86, 6, null),
					new ExpectedCellValue(sheetName, 86, 7, null),
					new ExpectedCellValue(sheetName, 86, 8, null),
					new ExpectedCellValue(sheetName, 86, 9, null),
					new ExpectedCellValue(sheetName, 86, 10, null),
					new ExpectedCellValue(sheetName, 86, 11, null),
					new ExpectedCellValue(sheetName, 86, 12, null),
					new ExpectedCellValue(sheetName, 86, 13, 7.2),
					new ExpectedCellValue(sheetName, 86, 14, 7.2),
					new ExpectedCellValue(sheetName, 86, 15, 7.2),
					new ExpectedCellValue(sheetName, 87, 2, "Power Supply Cable"),
					new ExpectedCellValue(sheetName, 87, 3, null),
					new ExpectedCellValue(sheetName, 87, 4, null),
					new ExpectedCellValue(sheetName, 87, 5, null),
					new ExpectedCellValue(sheetName, 87, 6, null),
					new ExpectedCellValue(sheetName, 87, 7, null),
					new ExpectedCellValue(sheetName, 87, 8, null),
					new ExpectedCellValue(sheetName, 87, 9, null),
					new ExpectedCellValue(sheetName, 87, 10, null),
					new ExpectedCellValue(sheetName, 87, 11, null),
					new ExpectedCellValue(sheetName, 87, 12, null),
					new ExpectedCellValue(sheetName, 87, 13, 0.4),
					new ExpectedCellValue(sheetName, 87, 14, 0.4),
					new ExpectedCellValue(sheetName, 87, 15, 0.4),
					new ExpectedCellValue(sheetName, 88, 2, "Printing Paper"),
					new ExpectedCellValue(sheetName, 88, 3, null),
					new ExpectedCellValue(sheetName, 88, 4, null),
					new ExpectedCellValue(sheetName, 88, 5, null),
					new ExpectedCellValue(sheetName, 88, 6, null),
					new ExpectedCellValue(sheetName, 88, 7, null),
					new ExpectedCellValue(sheetName, 88, 8, null),
					new ExpectedCellValue(sheetName, 88, 9, null),
					new ExpectedCellValue(sheetName, 88, 10, null),
					new ExpectedCellValue(sheetName, 88, 11, null),
					new ExpectedCellValue(sheetName, 88, 12, 4.7),
					new ExpectedCellValue(sheetName, 88, 13, null),
					new ExpectedCellValue(sheetName, 88, 14, 4.7),
					new ExpectedCellValue(sheetName, 88, 15, 4.7),
					new ExpectedCellValue(sheetName, 89, 2, "Quietkey Keyboard"),
					new ExpectedCellValue(sheetName, 89, 3, null),
					new ExpectedCellValue(sheetName, 89, 4, null),
					new ExpectedCellValue(sheetName, 89, 5, null),
					new ExpectedCellValue(sheetName, 89, 6, null),
					new ExpectedCellValue(sheetName, 89, 7, null),
					new ExpectedCellValue(sheetName, 89, 8, null),
					new ExpectedCellValue(sheetName, 89, 9, null),
					new ExpectedCellValue(sheetName, 89, 10, null),
					new ExpectedCellValue(sheetName, 89, 11, null),
					new ExpectedCellValue(sheetName, 89, 12, null),
					new ExpectedCellValue(sheetName, 89, 13, 4.5),
					new ExpectedCellValue(sheetName, 89, 14, 4.5),
					new ExpectedCellValue(sheetName, 89, 15, 4.5),
					new ExpectedCellValue(sheetName, 90, 2, "Rim"),
					new ExpectedCellValue(sheetName, 90, 3, null),
					new ExpectedCellValue(sheetName, 90, 4, 1.05),
					new ExpectedCellValue(sheetName, 90, 5, null),
					new ExpectedCellValue(sheetName, 90, 6, null),
					new ExpectedCellValue(sheetName, 90, 7, 1.05),
					new ExpectedCellValue(sheetName, 90, 8, null),
					new ExpectedCellValue(sheetName, 90, 9, null),
					new ExpectedCellValue(sheetName, 90, 10, null),
					new ExpectedCellValue(sheetName, 90, 11, null),
					new ExpectedCellValue(sheetName, 90, 12, null),
					new ExpectedCellValue(sheetName, 90, 13, null),
					new ExpectedCellValue(sheetName, 90, 14, null),
					new ExpectedCellValue(sheetName, 90, 15, 1.05),
					new ExpectedCellValue(sheetName, 91, 2, "ROME Guest Chair, green"),
					new ExpectedCellValue(sheetName, 91, 3, null),
					new ExpectedCellValue(sheetName, 91, 4, null),
					new ExpectedCellValue(sheetName, 91, 5, null),
					new ExpectedCellValue(sheetName, 91, 6, null),
					new ExpectedCellValue(sheetName, 91, 7, null),
					new ExpectedCellValue(sheetName, 91, 8, null),
					new ExpectedCellValue(sheetName, 91, 9, null),
					new ExpectedCellValue(sheetName, 91, 10, 150.3),
					new ExpectedCellValue(sheetName, 91, 11, null),
					new ExpectedCellValue(sheetName, 91, 12, null),
					new ExpectedCellValue(sheetName, 91, 13, null),
					new ExpectedCellValue(sheetName, 91, 14, 150.3),
					new ExpectedCellValue(sheetName, 91, 15, 150.3),
					new ExpectedCellValue(sheetName, 92, 2, "SAPPORO Whiteboard, black"),
					new ExpectedCellValue(sheetName, 92, 3, 1092.1),
					new ExpectedCellValue(sheetName, 92, 4, null),
					new ExpectedCellValue(sheetName, 92, 5, null),
					new ExpectedCellValue(sheetName, 92, 6, null),
					new ExpectedCellValue(sheetName, 92, 7, 1092.1),
					new ExpectedCellValue(sheetName, 92, 8, null),
					new ExpectedCellValue(sheetName, 92, 9, null),
					new ExpectedCellValue(sheetName, 92, 10, null),
					new ExpectedCellValue(sheetName, 92, 11, null),
					new ExpectedCellValue(sheetName, 92, 12, null),
					new ExpectedCellValue(sheetName, 92, 13, null),
					new ExpectedCellValue(sheetName, 92, 14, null),
					new ExpectedCellValue(sheetName, 92, 15, 1092.1),
					new ExpectedCellValue(sheetName, 93, 2, "SARAJEVO Whiteboard, blue"),
					new ExpectedCellValue(sheetName, 93, 3, 1092.1),
					new ExpectedCellValue(sheetName, 93, 4, null),
					new ExpectedCellValue(sheetName, 93, 5, null),
					new ExpectedCellValue(sheetName, 93, 6, null),
					new ExpectedCellValue(sheetName, 93, 7, 1092.1),
					new ExpectedCellValue(sheetName, 93, 8, null),
					new ExpectedCellValue(sheetName, 93, 9, null),
					new ExpectedCellValue(sheetName, 93, 10, null),
					new ExpectedCellValue(sheetName, 93, 11, null),
					new ExpectedCellValue(sheetName, 93, 12, null),
					new ExpectedCellValue(sheetName, 93, 13, null),
					new ExpectedCellValue(sheetName, 93, 14, null),
					new ExpectedCellValue(sheetName, 93, 15, 1092.1),
					new ExpectedCellValue(sheetName, 94, 2, "Screw on Hard Drive Mounting"),
					new ExpectedCellValue(sheetName, 94, 3, null),
					new ExpectedCellValue(sheetName, 94, 4, null),
					new ExpectedCellValue(sheetName, 94, 5, null),
					new ExpectedCellValue(sheetName, 94, 6, null),
					new ExpectedCellValue(sheetName, 94, 7, null),
					new ExpectedCellValue(sheetName, 94, 8, null),
					new ExpectedCellValue(sheetName, 94, 9, null),
					new ExpectedCellValue(sheetName, 94, 10, null),
					new ExpectedCellValue(sheetName, 94, 11, null),
					new ExpectedCellValue(sheetName, 94, 12, null),
					new ExpectedCellValue(sheetName, 94, 13, 0),
					new ExpectedCellValue(sheetName, 94, 14, 0),
					new ExpectedCellValue(sheetName, 94, 15, 0),
					new ExpectedCellValue(sheetName, 95, 2, "Screw on Mount CD/Tape Drive"),
					new ExpectedCellValue(sheetName, 95, 3, null),
					new ExpectedCellValue(sheetName, 95, 4, null),
					new ExpectedCellValue(sheetName, 95, 5, null),
					new ExpectedCellValue(sheetName, 95, 6, null),
					new ExpectedCellValue(sheetName, 95, 7, null),
					new ExpectedCellValue(sheetName, 95, 8, null),
					new ExpectedCellValue(sheetName, 95, 9, null),
					new ExpectedCellValue(sheetName, 95, 10, null),
					new ExpectedCellValue(sheetName, 95, 11, null),
					new ExpectedCellValue(sheetName, 95, 12, null),
					new ExpectedCellValue(sheetName, 95, 13, 0),
					new ExpectedCellValue(sheetName, 95, 14, 0),
					new ExpectedCellValue(sheetName, 95, 15, 0),
					new ExpectedCellValue(sheetName, 96, 2, "SEOUL Guest Chair, red"),
					new ExpectedCellValue(sheetName, 96, 3, null),
					new ExpectedCellValue(sheetName, 96, 4, null),
					new ExpectedCellValue(sheetName, 96, 5, null),
					new ExpectedCellValue(sheetName, 96, 6, null),
					new ExpectedCellValue(sheetName, 96, 7, null),
					new ExpectedCellValue(sheetName, 96, 8, null),
					new ExpectedCellValue(sheetName, 96, 9, null),
					new ExpectedCellValue(sheetName, 96, 10, 150.3),
					new ExpectedCellValue(sheetName, 96, 11, null),
					new ExpectedCellValue(sheetName, 96, 12, null),
					new ExpectedCellValue(sheetName, 96, 13, null),
					new ExpectedCellValue(sheetName, 96, 14, 150.3),
					new ExpectedCellValue(sheetName, 96, 15, 150.3),
					new ExpectedCellValue(sheetName, 97, 2, "Server - Enterprise Package"),
					new ExpectedCellValue(sheetName, 97, 3, null),
					new ExpectedCellValue(sheetName, 97, 4, null),
					new ExpectedCellValue(sheetName, 97, 5, null),
					new ExpectedCellValue(sheetName, 97, 6, null),
					new ExpectedCellValue(sheetName, 97, 7, null),
					new ExpectedCellValue(sheetName, 97, 8, null),
					new ExpectedCellValue(sheetName, 97, 9, null),
					new ExpectedCellValue(sheetName, 97, 10, null),
					new ExpectedCellValue(sheetName, 97, 11, null),
					new ExpectedCellValue(sheetName, 97, 12, null),
					new ExpectedCellValue(sheetName, 97, 13, 0),
					new ExpectedCellValue(sheetName, 97, 14, 0),
					new ExpectedCellValue(sheetName, 97, 15, 0),
					new ExpectedCellValue(sheetName, 98, 2, "Server - Teamwear Package"),
					new ExpectedCellValue(sheetName, 98, 3, null),
					new ExpectedCellValue(sheetName, 98, 4, null),
					new ExpectedCellValue(sheetName, 98, 5, null),
					new ExpectedCellValue(sheetName, 98, 6, null),
					new ExpectedCellValue(sheetName, 98, 7, null),
					new ExpectedCellValue(sheetName, 98, 8, null),
					new ExpectedCellValue(sheetName, 98, 9, null),
					new ExpectedCellValue(sheetName, 98, 10, null),
					new ExpectedCellValue(sheetName, 98, 11, null),
					new ExpectedCellValue(sheetName, 98, 12, null),
					new ExpectedCellValue(sheetName, 98, 13, 0),
					new ExpectedCellValue(sheetName, 98, 14, 0),
					new ExpectedCellValue(sheetName, 98, 15, 0),
					new ExpectedCellValue(sheetName, 99, 2, "Spike for LS-100"),
					new ExpectedCellValue(sheetName, 99, 3, null),
					new ExpectedCellValue(sheetName, 99, 4, null),
					new ExpectedCellValue(sheetName, 99, 5, null),
					new ExpectedCellValue(sheetName, 99, 6, null),
					new ExpectedCellValue(sheetName, 99, 7, null),
					new ExpectedCellValue(sheetName, 99, 8, 15),
					new ExpectedCellValue(sheetName, 99, 9, null),
					new ExpectedCellValue(sheetName, 99, 10, null),
					new ExpectedCellValue(sheetName, 99, 11, null),
					new ExpectedCellValue(sheetName, 99, 12, null),
					new ExpectedCellValue(sheetName, 99, 13, null),
					new ExpectedCellValue(sheetName, 99, 14, 15),
					new ExpectedCellValue(sheetName, 99, 15, 15),
					new ExpectedCellValue(sheetName, 100, 2, "ST.MORITZ Storage Unit/Drawers"),
					new ExpectedCellValue(sheetName, 100, 3, 295.6),
					new ExpectedCellValue(sheetName, 100, 4, null),
					new ExpectedCellValue(sheetName, 100, 5, null),
					new ExpectedCellValue(sheetName, 100, 6, null),
					new ExpectedCellValue(sheetName, 100, 7, 295.6),
					new ExpectedCellValue(sheetName, 100, 8, null),
					new ExpectedCellValue(sheetName, 100, 9, null),
					new ExpectedCellValue(sheetName, 100, 10, null),
					new ExpectedCellValue(sheetName, 100, 11, null),
					new ExpectedCellValue(sheetName, 100, 12, null),
					new ExpectedCellValue(sheetName, 100, 13, null),
					new ExpectedCellValue(sheetName, 100, 14, null),
					new ExpectedCellValue(sheetName, 100, 15, 295.6),
					new ExpectedCellValue(sheetName, 101, 2, "Stand for Loudspeakers LS-150"),
					new ExpectedCellValue(sheetName, 101, 3, null),
					new ExpectedCellValue(sheetName, 101, 4, null),
					new ExpectedCellValue(sheetName, 101, 5, null),
					new ExpectedCellValue(sheetName, 101, 6, null),
					new ExpectedCellValue(sheetName, 101, 7, null),
					new ExpectedCellValue(sheetName, 101, 8, 45),
					new ExpectedCellValue(sheetName, 101, 9, null),
					new ExpectedCellValue(sheetName, 101, 10, null),
					new ExpectedCellValue(sheetName, 101, 11, null),
					new ExpectedCellValue(sheetName, 101, 12, null),
					new ExpectedCellValue(sheetName, 101, 13, null),
					new ExpectedCellValue(sheetName, 101, 14, 45),
					new ExpectedCellValue(sheetName, 101, 15, 45),
					new ExpectedCellValue(sheetName, 102, 2, "SYDNEY Swivel Chair, green"),
					new ExpectedCellValue(sheetName, 102, 3, null),
					new ExpectedCellValue(sheetName, 102, 4, null),
					new ExpectedCellValue(sheetName, 102, 5, null),
					new ExpectedCellValue(sheetName, 102, 6, null),
					new ExpectedCellValue(sheetName, 102, 7, null),
					new ExpectedCellValue(sheetName, 102, 8, null),
					new ExpectedCellValue(sheetName, 102, 9, null),
					new ExpectedCellValue(sheetName, 102, 10, null),
					new ExpectedCellValue(sheetName, 102, 11, 148.1),
					new ExpectedCellValue(sheetName, 102, 12, null),
					new ExpectedCellValue(sheetName, 102, 13, null),
					new ExpectedCellValue(sheetName, 102, 14, 148.1),
					new ExpectedCellValue(sheetName, 102, 15, 148.1),
					new ExpectedCellValue(sheetName, 103, 2, "Team Work Computer 533 MHz"),
					new ExpectedCellValue(sheetName, 103, 3, null),
					new ExpectedCellValue(sheetName, 103, 4, null),
					new ExpectedCellValue(sheetName, 103, 5, null),
					new ExpectedCellValue(sheetName, 103, 6, null),
					new ExpectedCellValue(sheetName, 103, 7, null),
					new ExpectedCellValue(sheetName, 103, 8, null),
					new ExpectedCellValue(sheetName, 103, 9, null),
					new ExpectedCellValue(sheetName, 103, 10, null),
					new ExpectedCellValue(sheetName, 103, 11, null),
					new ExpectedCellValue(sheetName, 103, 12, null),
					new ExpectedCellValue(sheetName, 103, 13, 144),
					new ExpectedCellValue(sheetName, 103, 14, 144),
					new ExpectedCellValue(sheetName, 103, 15, 144),
					new ExpectedCellValue(sheetName, 104, 2, "TOKYO Guest Chair, blue"),
					new ExpectedCellValue(sheetName, 104, 3, null),
					new ExpectedCellValue(sheetName, 104, 4, null),
					new ExpectedCellValue(sheetName, 104, 5, null),
					new ExpectedCellValue(sheetName, 104, 6, null),
					new ExpectedCellValue(sheetName, 104, 7, null),
					new ExpectedCellValue(sheetName, 104, 8, null),
					new ExpectedCellValue(sheetName, 104, 9, null),
					new ExpectedCellValue(sheetName, 104, 10, 150.3),
					new ExpectedCellValue(sheetName, 104, 11, null),
					new ExpectedCellValue(sheetName, 104, 12, null),
					new ExpectedCellValue(sheetName, 104, 13, null),
					new ExpectedCellValue(sheetName, 104, 14, 150.3),
					new ExpectedCellValue(sheetName, 104, 15, 150.3),
					new ExpectedCellValue(sheetName, 105, 2, "Touring Bicycle"),
					new ExpectedCellValue(sheetName, 105, 3, 350.595),
					new ExpectedCellValue(sheetName, 105, 4, null),
					new ExpectedCellValue(sheetName, 105, 5, null),
					new ExpectedCellValue(sheetName, 105, 6, null),
					new ExpectedCellValue(sheetName, 105, 7, 350.595),
					new ExpectedCellValue(sheetName, 105, 8, null),
					new ExpectedCellValue(sheetName, 105, 9, null),
					new ExpectedCellValue(sheetName, 105, 10, null),
					new ExpectedCellValue(sheetName, 105, 11, null),
					new ExpectedCellValue(sheetName, 105, 12, null),
					new ExpectedCellValue(sheetName, 105, 13, null),
					new ExpectedCellValue(sheetName, 105, 14, null),
					new ExpectedCellValue(sheetName, 105, 15, 350.595),
					new ExpectedCellValue(sheetName, 106, 2, "Tweeter speaker unit 4\" 100W"),
					new ExpectedCellValue(sheetName, 106, 3, null),
					new ExpectedCellValue(sheetName, 106, 4, null),
					new ExpectedCellValue(sheetName, 106, 5, null),
					new ExpectedCellValue(sheetName, 106, 6, null),
					new ExpectedCellValue(sheetName, 106, 7, null),
					new ExpectedCellValue(sheetName, 106, 8, 15),
					new ExpectedCellValue(sheetName, 106, 9, null),
					new ExpectedCellValue(sheetName, 106, 10, null),
					new ExpectedCellValue(sheetName, 106, 11, null),
					new ExpectedCellValue(sheetName, 106, 12, null),
					new ExpectedCellValue(sheetName, 106, 13, null),
					new ExpectedCellValue(sheetName, 106, 14, 15),
					new ExpectedCellValue(sheetName, 106, 15, 15),
					new ExpectedCellValue(sheetName, 107, 2, "Ultra 160/M SCSI Controller"),
					new ExpectedCellValue(sheetName, 107, 3, null),
					new ExpectedCellValue(sheetName, 107, 4, null),
					new ExpectedCellValue(sheetName, 107, 5, null),
					new ExpectedCellValue(sheetName, 107, 6, null),
					new ExpectedCellValue(sheetName, 107, 7, null),
					new ExpectedCellValue(sheetName, 107, 8, null),
					new ExpectedCellValue(sheetName, 107, 9, null),
					new ExpectedCellValue(sheetName, 107, 10, null),
					new ExpectedCellValue(sheetName, 107, 11, null),
					new ExpectedCellValue(sheetName, 107, 12, null),
					new ExpectedCellValue(sheetName, 107, 13, 5.4),
					new ExpectedCellValue(sheetName, 107, 14, 5.4),
					new ExpectedCellValue(sheetName, 107, 15, 5.4),
					new ExpectedCellValue(sheetName, 108, 2, "Webcam"),
					new ExpectedCellValue(sheetName, 108, 3, null),
					new ExpectedCellValue(sheetName, 108, 4, null),
					new ExpectedCellValue(sheetName, 108, 5, null),
					new ExpectedCellValue(sheetName, 108, 6, null),
					new ExpectedCellValue(sheetName, 108, 7, null),
					new ExpectedCellValue(sheetName, 108, 8, null),
					new ExpectedCellValue(sheetName, 108, 9, null),
					new ExpectedCellValue(sheetName, 108, 10, null),
					new ExpectedCellValue(sheetName, 108, 11, null),
					new ExpectedCellValue(sheetName, 108, 12, null),
					new ExpectedCellValue(sheetName, 108, 13, 1.1),
					new ExpectedCellValue(sheetName, 108, 14, 1.1),
					new ExpectedCellValue(sheetName, 108, 15, 1.1),
					new ExpectedCellValue(sheetName, 109, 2, "Grand Total"),
					new ExpectedCellValue(sheetName, 109, 3, 15563.087),
					new ExpectedCellValue(sheetName, 109, 4, 1.05),
					new ExpectedCellValue(sheetName, 109, 5, 255.271),
					new ExpectedCellValue(sheetName, 109, 6, 6.49),
					new ExpectedCellValue(sheetName, 109, 7, 15825.898),
					new ExpectedCellValue(sheetName, 109, 8, 406),
					new ExpectedCellValue(sheetName, 109, 9, 103.6),
					new ExpectedCellValue(sheetName, 109, 10, 1256.9),
					new ExpectedCellValue(sheetName, 109, 11, 2949.3),
					new ExpectedCellValue(sheetName, 109, 12, 4.7),
					new ExpectedCellValue(sheetName, 109, 13, 873.4),
					new ExpectedCellValue(sheetName, 109, 14, 5593.9),
					new ExpectedCellValue(sheetName, 109, 15, 21419.798),
				});
			}
		}

		[TestMethod]
		[DeploymentItem(@"..\..\Workbooks\PivotTables\PivotTableWithReportFilter.xlsx")]
		public void PivotTableWithReportFilter()
		{
			var file = new FileInfo("PivotTableWithReportFilter.xlsx");
			Assert.IsTrue(file.Exists);
			using (var newFile = new TempTestFile())
			{
				string sheetName = "Sheet4";
				using (var package = new ExcelPackage(file))
				{
					var worksheet = package.Workbook.Worksheets[sheetName];
					var pivotTable = worksheet.PivotTables["PivotTable1"];
					var cacheDefinition = package.Workbook.PivotCacheDefinitions.Single();
					cacheDefinition.UpdateData();
					ExcelPivotTableTest.CheckPivotTableAddress(new ExcelAddress("B3:H16"), pivotTable.Address);
					Assert.AreEqual(8, pivotTable.Fields.Count);
					package.SaveAs(newFile.File);
				}
				TestHelperUtility.ValidateWorksheet(newFile.File, sheetName, new[]
				{
					new ExpectedCellValue(sheetName, 1, 2, "Reorder Quantity"),
					new ExpectedCellValue(sheetName, 1, 3, 100),
					new ExpectedCellValue(sheetName, 3, 2, "Sum of Unit Cost"),
					new ExpectedCellValue(sheetName, 3, 3, "Column Labels"),
					new ExpectedCellValue(sheetName, 4, 3, "FINISHED"),
					new ExpectedCellValue(sheetName, 4, 7, "FINISHED Total"),
					new ExpectedCellValue(sheetName, 4, 8, "Grand Total"),
					new ExpectedCellValue(sheetName, 5, 2, "Row Labels"),
					new ExpectedCellValue(sheetName, 5, 4, "01587796"),
					new ExpectedCellValue(sheetName, 5, 5, "20000"),
					new ExpectedCellValue(sheetName, 5, 6, "32456123"),
					new ExpectedCellValue(sheetName, 6, 2, "Back Hub"),
					new ExpectedCellValue(sheetName, 6, 3, 12.452),
					new ExpectedCellValue(sheetName, 6, 4, null),
					new ExpectedCellValue(sheetName, 6, 5, null),
					new ExpectedCellValue(sheetName, 6, 6, null),
					new ExpectedCellValue(sheetName, 6, 7, 12.452),
					new ExpectedCellValue(sheetName, 6, 8, 12.452),
					new ExpectedCellValue(sheetName, 7, 2, "Back Wheel"),
					new ExpectedCellValue(sheetName, 7, 3, 129.682),
					new ExpectedCellValue(sheetName, 7, 4, null),
					new ExpectedCellValue(sheetName, 7, 5, null),
					new ExpectedCellValue(sheetName, 7, 6, null),
					new ExpectedCellValue(sheetName, 7, 7, 129.682),
					new ExpectedCellValue(sheetName, 7, 8, 129.682),
					new ExpectedCellValue(sheetName, 8, 2, "Bicycle"),
					new ExpectedCellValue(sheetName, 8, 3, 350.595),
					new ExpectedCellValue(sheetName, 8, 4, null),
					new ExpectedCellValue(sheetName, 8, 5, null),
					new ExpectedCellValue(sheetName, 8, 6, null),
					new ExpectedCellValue(sheetName, 8, 7, 350.595),
					new ExpectedCellValue(sheetName, 8, 8, 350.595),
					new ExpectedCellValue(sheetName, 9, 2, "Brake"),
					new ExpectedCellValue(sheetName, 9, 3, 9.765),
					new ExpectedCellValue(sheetName, 9, 4, null),
					new ExpectedCellValue(sheetName, 9, 5, null),
					new ExpectedCellValue(sheetName, 9, 6, null),
					new ExpectedCellValue(sheetName, 9, 7, 9.765),
					new ExpectedCellValue(sheetName, 9, 8, 9.765),
					new ExpectedCellValue(sheetName, 10, 2, "Chain"),
					new ExpectedCellValue(sheetName, 10, 3, null),
					new ExpectedCellValue(sheetName, 10, 4, null),
					new ExpectedCellValue(sheetName, 10, 5, null),
					new ExpectedCellValue(sheetName, 10, 6, 1.99),
					new ExpectedCellValue(sheetName, 10, 7, 1.99),
					new ExpectedCellValue(sheetName, 10, 8, 1.99),
					new ExpectedCellValue(sheetName, 11, 2, "Chain Assy"),
					new ExpectedCellValue(sheetName, 11, 3, 13.157),
					new ExpectedCellValue(sheetName, 11, 4, null),
					new ExpectedCellValue(sheetName, 11, 5, null),
					new ExpectedCellValue(sheetName, 11, 6, null),
					new ExpectedCellValue(sheetName, 11, 7, 13.157),
					new ExpectedCellValue(sheetName, 11, 8, 13.157),
					new ExpectedCellValue(sheetName, 12, 2, "Front Hub"),
					new ExpectedCellValue(sheetName, 12, 3, 12.441),
					new ExpectedCellValue(sheetName, 12, 4, null),
					new ExpectedCellValue(sheetName, 12, 5, null),
					new ExpectedCellValue(sheetName, 12, 6, null),
					new ExpectedCellValue(sheetName, 12, 7, 12.441),
					new ExpectedCellValue(sheetName, 12, 8, 12.441),
					new ExpectedCellValue(sheetName, 13, 2, "Front Wheel"),
					new ExpectedCellValue(sheetName, 13, 3, null),
					new ExpectedCellValue(sheetName, 13, 4, null),
					new ExpectedCellValue(sheetName, 13, 5, 129.671),
					new ExpectedCellValue(sheetName, 13, 6, null),
					new ExpectedCellValue(sheetName, 13, 7, 129.671),
					new ExpectedCellValue(sheetName, 13, 8, 129.671),
					new ExpectedCellValue(sheetName, 14, 2, "Hand rear wheel Brake"),
					new ExpectedCellValue(sheetName, 14, 3, null),
					new ExpectedCellValue(sheetName, 14, 4, null),
					new ExpectedCellValue(sheetName, 14, 5, null),
					new ExpectedCellValue(sheetName, 14, 6, 4.5),
					new ExpectedCellValue(sheetName, 14, 7, 4.5),
					new ExpectedCellValue(sheetName, 14, 8, 4.5),
					new ExpectedCellValue(sheetName, 15, 2, "Rim"),
					new ExpectedCellValue(sheetName, 15, 3, null),
					new ExpectedCellValue(sheetName, 15, 4, 1.05),
					new ExpectedCellValue(sheetName, 15, 5, null),
					new ExpectedCellValue(sheetName, 15, 6, null),
					new ExpectedCellValue(sheetName, 15, 7, 1.05),
					new ExpectedCellValue(sheetName, 15, 8, 1.05),
					new ExpectedCellValue(sheetName, 16, 2, "Grand Total"),
					new ExpectedCellValue(sheetName, 16, 3, 528.092),
					new ExpectedCellValue(sheetName, 16, 4, 1.05),
					new ExpectedCellValue(sheetName, 16, 5, 129.671),
					new ExpectedCellValue(sheetName, 16, 6, 6.49),
					new ExpectedCellValue(sheetName, 16, 7, 665.303),
					new ExpectedCellValue(sheetName, 16, 8, 665.303),
				});
			}
		}
		#endregion
	}
}